// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using OF.Data.Database;

namespace OF.Data
{
    public partial class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext()
        {
        }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Alert> Alerts { get; set; } = null!;
        public virtual DbSet<Asset> Assets { get; set; } = null!;
        public virtual DbSet<AssetsStaging> AssetsStagings { get; set; } = null!;
        public virtual DbSet<ChangeOrder> ChangeOrders { get; set; } = null!;
        public virtual DbSet<ChangeOrderAddress> ChangeOrderAddresses { get; set; } = null!;
        public virtual DbSet<ChangeOrderComment> ChangeOrderComments { get; set; } = null!;
        public virtual DbSet<ChangeOrderContact> ChangeOrderContacts { get; set; } = null!;
        public virtual DbSet<ChangeOrderHeader> ChangeOrderHeaders { get; set; } = null!;
        public virtual DbSet<ChangeOrderLine> ChangeOrderLines { get; set; } = null!;
        public virtual DbSet<CpqAttribute> CpqAttributes { get; set; } = null!;
        public virtual DbSet<CpqAttributeLookup> CpqAttributeLookups { get; set; } = null!;
        public virtual DbSet<CpqAttributeLookupStaging> CpqAttributeLookupStagings { get; set; } = null!;
        public virtual DbSet<CpqAttributeStaging> CpqAttributeStagings { get; set; } = null!;
        public virtual DbSet<CpqFamily> CpqFamilies { get; set; } = null!;
        public virtual DbSet<CpqFamilyStaging> CpqFamilyStagings { get; set; } = null!;
        public virtual DbSet<CpqGeneric> CpqGenerics { get; set; } = null!;
        public virtual DbSet<CpqGenericRating> CpqGenericRatings { get; set; } = null!;
        public virtual DbSet<CpqGenericRatingStaging> CpqGenericRatingStagings { get; set; } = null!;
        public virtual DbSet<CpqGenericStaging> CpqGenericStagings { get; set; } = null!;
        public virtual DbSet<CpqGenericSubstitution> CpqGenericSubstitutions { get; set; } = null!;
        public virtual DbSet<CpqGenericSubstitutionStaging> CpqGenericSubstitutionStagings { get; set; } = null!;
        public virtual DbSet<CpqGenericToGeneric> CpqGenericToGenerics { get; set; } = null!;
        public virtual DbSet<CpqGenericToGenericStaging> CpqGenericToGenericStagings { get; set; } = null!;
        public virtual DbSet<CpqItem> CpqItems { get; set; } = null!;
        public virtual DbSet<CpqItemAttributeValue> CpqItemAttributeValues { get; set; } = null!;
        public virtual DbSet<CpqItemAttributeValueStaging> CpqItemAttributeValueStagings { get; set; } = null!;
        public virtual DbSet<CpqItemStaging> CpqItemStagings { get; set; } = null!;
        public virtual DbSet<CpqLine> CpqLines { get; set; } = null!;
        public virtual DbSet<CpqLineAttributePurpose> CpqLineAttributePurposes { get; set; } = null!;
        public virtual DbSet<CpqLineAttributePurposeStaging> CpqLineAttributePurposeStagings { get; set; } = null!;
        public virtual DbSet<CpqLineSellingRule> CpqLineSellingRules { get; set; } = null!;
        public virtual DbSet<CpqLineSellingRuleStaging> CpqLineSellingRuleStagings { get; set; } = null!;
        public virtual DbSet<CpqLineStaging> CpqLineStagings { get; set; } = null!;
        public virtual DbSet<CpqPurpose> CpqPurposes { get; set; } = null!;
        public virtual DbSet<CpqPurposeStaging> CpqPurposeStagings { get; set; } = null!;
        public virtual DbSet<CpqRegion> CpqRegions { get; set; } = null!;
        public virtual DbSet<CpqRegionCurrency> CpqRegionCurrencies { get; set; } = null!;
        public virtual DbSet<CpqRegionCurrencyStaging> CpqRegionCurrencyStagings { get; set; } = null!;
        public virtual DbSet<CpqRegionGeneric> CpqRegionGenerics { get; set; } = null!;
        public virtual DbSet<CpqRegionGenericStaging> CpqRegionGenericStagings { get; set; } = null!;
        public virtual DbSet<CpqRegionStaging> CpqRegionStagings { get; set; } = null!;
        public virtual DbSet<CpqRelatedSpecificSubstitution> CpqRelatedSpecificSubstitutions { get; set; } = null!;
        public virtual DbSet<CpqRelatedSpecificSubstitutionStaging> CpqRelatedSpecificSubstitutionStagings { get; set; } = null!;
        public virtual DbSet<CpqService> CpqServices { get; set; } = null!;
        public virtual DbSet<CpqServiceStaging> CpqServiceStagings { get; set; } = null!;
        public virtual DbSet<CpqLog> CpqLogs { get; set; } = null!;
        public virtual DbSet<CpqVersion> CpqVersions { get; set; } = null!;
        public virtual DbSet<CpqVersionStaging> CpqVersionStagings { get; set; } = null!;
        public virtual DbSet<DataRefresh> DataRefreshes { get; set; } = null!;
        public virtual DbSet<Header> Headers { get; set; } = null!;
        public virtual DbSet<Line> Lines { get; set; } = null!;
        public virtual DbSet<Note> Notes { get; set; } = null!;
        public virtual DbSet<ProductHierarchyStaging> ProductHierarchyStagings { get; set; } = null!;
        public virtual DbSet<ProductItem> ProductItems { get; set; } = null!;
        public virtual DbSet<ProductItemsStaging> ProductItemsStagings { get; set; } = null!;
        public virtual DbSet<ProductItemsSyncList> ProductItemsSyncList { get; set; } = null!;
        public virtual DbSet<ProcessingError> ProcessingErrors { get; set; } = null!;
        public virtual DbSet<Reservation> Reservations { get; set; } = null!;
        public virtual DbSet<RetrofitCache> RetrofitCaches { get; set; } = null!;
        public virtual DbSet<Ringfence> Ringfences { get; set; } = null!;
        public virtual DbSet<RingfenceItem> RingfenceItems { get; set; } = null!;
        public virtual DbSet<User> Users { get; set; } = null!;
        public virtual DbSet<View> Views { get; set; } = null!;
        public virtual DbSet<ViewRecipient> ViewRecipients { get; set; } = null!;
        public virtual DbSet<VwAllAttribute> VwAllAttributes { get; set; } = null!;
        public virtual DbSet<VwAssetItem> VwAssetItems { get; set; } = null!;
        public virtual DbSet<VwHeader> VwHeaders { get; set; } = null!;
        public virtual DbSet<WarehouseItem> WarehouseItems { get; set; } = null!;
        public virtual DbSet<WarehouseItemsStaging> WarehouseItemsStagings { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Alert>(entity =>
            {
                entity.Property(e => e.AffectedUser).HasMaxLength(200);
            });

            modelBuilder.Entity<Asset>(entity =>
            {
                entity.Property(e => e.Id).HasMaxLength(100);

                entity.Property(e => e.AgreementNumber).HasMaxLength(100);

                entity.Property(e => e.CustomerName).HasMaxLength(100);

                entity.Property(e => e.CustomerNumber).HasMaxLength(100);

                entity.Property(e => e.Description).HasMaxLength(100);

                entity.Property(e => e.Division).HasMaxLength(100);

                entity.Property(e => e.Facility).HasMaxLength(100);

                entity.Property(e => e.IndividualItemNumber).HasMaxLength(100);

                entity.Property(e => e.InternationalSizeRating).HasMaxLength(100);

                entity.Property(e => e.IonlastModified).HasColumnName("IONLastModified");

                entity.Property(e => e.ItemNumber).HasMaxLength(100);

                entity.Property(e => e.ManufacturerName).HasMaxLength(100);

                entity.Property(e => e.OwnerServiceCenter).HasMaxLength(100);

                entity.Property(e => e.ProductCategory).HasMaxLength(100);

                entity.Property(e => e.ProductGroup).HasMaxLength(100);

                entity.Property(e => e.Remark).HasMaxLength(100);

                entity.Property(e => e.ServiceCenter).HasMaxLength(100);

                entity.Property(e => e.ShipAddress1).HasMaxLength(100);

                entity.Property(e => e.ShipAddress3).HasMaxLength(100);

                entity.Property(e => e.Status).HasMaxLength(100);

                entity.Property(e => e.StatusCode).HasMaxLength(100);

                entity.Property(e => e.TelemetryStatus).HasMaxLength(100);

                entity.Property(e => e.UsSizeRating).HasMaxLength(100);

                entity.Property(e => e.Warehouse).HasMaxLength(100);

                entity.Property(e => e.WarehouseLocation).HasMaxLength(100);
            });

            modelBuilder.Entity<AssetsStaging>(entity =>
            {
                entity.ToTable("AssetsStaging");

                entity.Property(e => e.Id).HasMaxLength(100);

                entity.Property(e => e.AgreementNumber).HasMaxLength(100);

                entity.Property(e => e.CustomerName).HasMaxLength(100);

                entity.Property(e => e.CustomerNumber).HasMaxLength(100);

                entity.Property(e => e.Description).HasMaxLength(100);

                entity.Property(e => e.Division).HasMaxLength(100);

                entity.Property(e => e.Facility).HasMaxLength(100);

                entity.Property(e => e.IndividualItemNumber).HasMaxLength(100);

                entity.Property(e => e.InternationalSizeRating).HasMaxLength(100);

                entity.Property(e => e.IonlastModified).HasColumnName("IONLastModified");

                entity.Property(e => e.ItemNumber).HasMaxLength(100);

                entity.Property(e => e.ManufacturerName).HasMaxLength(100);

                entity.Property(e => e.OwnerServiceCenter).HasMaxLength(100);

                entity.Property(e => e.ProductCategory).HasMaxLength(100);

                entity.Property(e => e.ProductGroup).HasMaxLength(100);

                entity.Property(e => e.Remark).HasMaxLength(100);

                entity.Property(e => e.ServiceCenter).HasMaxLength(100);

                entity.Property(e => e.ShipAddress1).HasMaxLength(100);

                entity.Property(e => e.ShipAddress3).HasMaxLength(100);

                entity.Property(e => e.Status).HasMaxLength(100);

                entity.Property(e => e.StatusCode).HasMaxLength(100);

                entity.Property(e => e.TelemetryStatus).HasMaxLength(100);

                entity.Property(e => e.UsSizeRating).HasMaxLength(100);

                entity.Property(e => e.Warehouse).HasMaxLength(100);

                entity.Property(e => e.WarehouseLocation).HasMaxLength(100);
            });

            modelBuilder.Entity<ChangeOrder>(entity =>
            {
                entity.Property(e => e.ArmcontactId).HasColumnName("ARMContactId");

                entity.HasOne(d => d.Armcontact)
                    .WithMany(p => p.ChangeOrderArmcontacts)
                    .HasForeignKey(d => d.ArmcontactId);

                entity.HasOne(d => d.BillingContact)
                    .WithMany(p => p.ChangeOrderBillingContacts)
                    .HasForeignKey(d => d.BillingContactId);

                entity.HasOne(d => d.Header)
                    .WithMany(p => p.ChangeOrders)
                    .HasForeignKey(d => d.HeaderId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.InvoiceAddress)
                    .WithMany(p => p.ChangeOrderInvoiceAddresses)
                    .HasForeignKey(d => d.InvoiceAddressId);

                entity.HasOne(d => d.PrimaryContact)
                    .WithMany(p => p.ChangeOrderPrimaryContacts)
                    .HasForeignKey(d => d.PrimaryContactId);

                entity.HasOne(d => d.SiteAddress)
                    .WithMany(p => p.ChangeOrderSiteAddresses)
                    .HasForeignKey(d => d.SiteAddressId);

                entity.HasOne(d => d.SiteContact)
                    .WithMany(p => p.ChangeOrderSiteContacts)
                    .HasForeignKey(d => d.SiteContactId);
            });

            modelBuilder.Entity<ChangeOrderAddress>(entity =>
            {
                entity.Property(e => e.AddressName).HasMaxLength(1000);

                entity.Property(e => e.City).HasMaxLength(200);

                entity.Property(e => e.Country).HasMaxLength(200);

                entity.Property(e => e.M3number)
                    .HasMaxLength(200)
                    .HasColumnName("M3Number");

                entity.Property(e => e.SalesforceId).HasMaxLength(200);

                entity.Property(e => e.StateOrProvince).HasMaxLength(200);

                entity.Property(e => e.Street).HasMaxLength(200);

                entity.Property(e => e.ZipOrPostalCode).HasMaxLength(200);
            });

            modelBuilder.Entity<ChangeOrderComment>(entity =>
            {
                entity.HasOne(d => d.ChangeOrder)
                    .WithMany(p => p.ChangeOrderComments)
                    .HasForeignKey(d => d.ChangeOrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<ChangeOrderContact>(entity =>
            {
                entity.Property(e => e.Email).HasMaxLength(200);

                entity.Property(e => e.FirstName).HasMaxLength(200);

                entity.Property(e => e.LastName).HasMaxLength(200);

                entity.Property(e => e.M3number)
                    .HasMaxLength(200)
                    .HasColumnName("M3Number");

                entity.Property(e => e.Mobile).HasMaxLength(200);

                entity.Property(e => e.Phone).HasMaxLength(200);

                entity.Property(e => e.SalesforceId).HasMaxLength(200);

                entity.Property(e => e.Segment).HasMaxLength(200);

                entity.Property(e => e.Title).HasMaxLength(200);
            });

            modelBuilder.Entity<ChangeOrderHeader>(entity =>
            {
                entity.HasKey(e => e.ChangeOrderId);

                entity.Property(e => e.ChangeOrderId).ValueGeneratedNever();

                entity.Property(e => e.CorrelationId).HasMaxLength(500);

                entity.Property(e => e.JobAic)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("JobAIC");

                entity.Property(e => e.Poamount)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("POAmount");

                entity.Property(e => e.Ponumber)
                    .HasMaxLength(200)
                    .IsUnicode(false)
                    .HasColumnName("PONumber");

                entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.PriceAdjustment).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.PriceBase).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ProjectCode)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.RateType)
                    .HasMaxLength(200)
                    .IsUnicode(false);

                entity.Property(e => e.TargetCustomerAmount).HasColumnType("decimal(18, 2)");

                entity.HasOne(d => d.ChangeOrder)
                    .WithOne(p => p.ChangeOrderHeader)
                    .HasForeignKey<ChangeOrderHeader>(d => d.ChangeOrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Header)
                    .WithMany(p => p.ChangeOrderHeaders)
                    .HasForeignKey(d => d.HeaderId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<ChangeOrderLine>(entity =>
            {
                entity.Property(e => e.Attributes).HasMaxLength(2000);

                entity.Property(e => e.CorrelationId).HasMaxLength(500);

                entity.Property(e => e.GenericItemNumber).HasMaxLength(200);

                entity.Property(e => e.ItemNumber).HasMaxLength(200);

                entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Quantity).HasDefaultValueSql("((0.0000000000000000e+000))");

                entity.Property(e => e.Warehouse)
                    .HasMaxLength(200)
                    .HasDefaultValueSql("(N'')");

                entity.HasOne(d => d.ChangeOrder)
                    .WithMany(p => p.ChangeOrderLines)
                    .HasForeignKey(d => d.ChangeOrderId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Line)
                    .WithMany(p => p.ChangeOrderLines)
                    .HasForeignKey(d => d.LineId)
                    .HasConstraintName("FK_ChangeOrderLines_ChangeOrderLines_LineId");
            });

            modelBuilder.Entity<CpqAttribute>(entity =>
            {
                entity.ToTable("CPQ_Attribute");

                entity.HasIndex(e => e.AttributeDescription, "CPQ_AttributeDescription_UC")
                    .IsUnique();

                entity.HasIndex(e => e.Cpqattribute1, "CPQ_Attribute_UC")
                    .IsUnique();

                entity.Property(e => e.AttributeDescription).HasMaxLength(40);

                entity.Property(e => e.AttributeName).HasMaxLength(100);

                entity.Property(e => e.Cpqattribute1)
                    .HasMaxLength(40)
                    .HasColumnName("CPQAttribute");

                entity.Property(e => e.DataType).HasMaxLength(6);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqAttributeLookup>(entity =>
            {
                entity.ToTable("CPQ_AttributeLookup");

                entity.Property(e => e.Value).HasMaxLength(100);
            });

            modelBuilder.Entity<CpqAttributeLookupStaging>(entity =>
            {
                entity.ToTable("CPQ_AttributeLookup_Staging");

                entity.Property(e => e.Value).HasMaxLength(100);
            });

            modelBuilder.Entity<CpqAttributeStaging>(entity =>
            {
                entity.ToTable("CPQ_Attribute_Staging");

                entity.Property(e => e.AttributeDescription).HasMaxLength(40);

                entity.Property(e => e.AttributeName).HasMaxLength(100);

                entity.Property(e => e.Cpqattribute)
                    .HasMaxLength(40)
                    .HasColumnName("CPQAttribute");

                entity.Property(e => e.DataType).HasMaxLength(6);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqFamily>(entity =>
            {
                entity.ToTable("CPQ_Family");

                entity.Property(e => e.FamilyDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<CpqFamilyStaging>(entity =>
            {
                entity.ToTable("CPQ_Family_Staging");

                entity.Property(e => e.FamilyDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<CpqGeneric>(entity =>
            {
                entity.ToTable("CPQ_Generic");

                entity.HasIndex(e => e.GenericCode, "CPQ_Generic_UC")
                    .IsUnique();

                entity.HasIndex(e => e.LineId, "IX_CPQ_Generic_LineId");

                entity.Property(e => e.AmperageLimit)
                    .HasMaxLength(100)
                    .HasColumnName("Amperage_Limit");

                entity.Property(e => e.CableM3itemNumber)
                    .HasMaxLength(100)
                    .HasColumnName("Cable_M3ItemNumber");

                entity.Property(e => e.CableSizeAwg)
                    .HasMaxLength(10)
                    .HasColumnName("Cable_Size_AWG");

                entity.Property(e => e.CableSizeMm)
                    .HasMaxLength(10)
                    .HasColumnName("Cable_Size_mm");

                entity.Property(e => e.CableType).HasMaxLength(100);

                entity.Property(e => e.Conductors).HasMaxLength(100);

                entity.Property(e => e.ConfigurationType).HasMaxLength(100);

                entity.Property(e => e.CpqSequence).HasColumnName("CPQ_Sequence");

                entity.Property(e => e.GenericCode).HasMaxLength(20);

                entity.Property(e => e.GenericDescription).HasMaxLength(255);

                entity.Property(e => e.IsFuel).HasMaxLength(10);

                entity.Property(e => e.IsMeter).HasMaxLength(10);

                entity.Property(e => e.M3Type)
                    .HasMaxLength(15)
                    .HasColumnName("M3_Type");

                entity.Property(e => e.RatingIntl)
                    .HasMaxLength(50)
                    .HasColumnName("Rating_Intl");

                entity.Property(e => e.RatingUs)
                    .HasMaxLength(50)
                    .HasColumnName("Rating_US");

                entity.Property(e => e.Rehire).HasMaxLength(3);

                entity.Property(e => e.RentalTermDays).HasColumnName("Rental_Term_Days");

                entity.Property(e => e.ShiftFactor).HasMaxLength(100);

                entity.Property(e => e.UomIntl)
                    .HasMaxLength(50)
                    .HasColumnName("UOM_Intl");

                entity.Property(e => e.UomUs)
                    .HasMaxLength(50)
                    .HasColumnName("UOM_US");

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.Line)
                    .WithMany(p => p.CpqGenerics)
                    .HasForeignKey(d => d.LineId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_Line_Id_FK");
            });

            modelBuilder.Entity<CpqGenericRating>(entity =>
            {
                entity.ToTable("CPQ_GenericRating");

                entity.Property(e => e.GenericCode).HasMaxLength(20);

                entity.Property(e => e.RatingIntl).HasColumnName("Rating_Intl");
            });

            modelBuilder.Entity<CpqGenericRatingStaging>(entity =>
            {
                entity.ToTable("CPQ_GenericRating_Staging");

                entity.Property(e => e.GenericCode).HasMaxLength(20);

                entity.Property(e => e.RatingIntl).HasColumnName("Rating_Intl");
            });

            modelBuilder.Entity<CpqGenericStaging>(entity =>
            {
                entity.ToTable("CPQ_Generic_Staging");

                entity.Property(e => e.AmperageLimit)
                    .HasMaxLength(100)
                    .HasColumnName("Amperage_Limit");

                entity.Property(e => e.CableM3itemNumber)
                    .HasMaxLength(100)
                    .HasColumnName("Cable_M3ItemNumber");

                entity.Property(e => e.CableSizeAwg)
                    .HasMaxLength(10)
                    .HasColumnName("Cable_Size_AWG");

                entity.Property(e => e.CableSizeMm)
                    .HasMaxLength(10)
                    .HasColumnName("Cable_Size_mm");

                entity.Property(e => e.CableType).HasMaxLength(100);

                entity.Property(e => e.Conductors).HasMaxLength(100);

                entity.Property(e => e.ConfigurationType).HasMaxLength(100);

                entity.Property(e => e.CpqSequence).HasColumnName("CPQ_Sequence");

                entity.Property(e => e.GenericCode).HasMaxLength(20);

                entity.Property(e => e.GenericDescription).HasMaxLength(255);

                entity.Property(e => e.IsFuel).HasMaxLength(10);

                entity.Property(e => e.IsMeter).HasMaxLength(10);

                entity.Property(e => e.M3Type)
                    .HasMaxLength(15)
                    .HasColumnName("M3_Type");

                entity.Property(e => e.RatingIntl)
                    .HasMaxLength(50)
                    .HasColumnName("Rating_Intl");

                entity.Property(e => e.RatingUs)
                    .HasMaxLength(50)
                    .HasColumnName("Rating_US");

                entity.Property(e => e.Rehire).HasMaxLength(3);

                entity.Property(e => e.RentalTermDays).HasColumnName("Rental_Term_Days");

                entity.Property(e => e.ShiftFactor).HasMaxLength(100);

                entity.Property(e => e.UomIntl)
                    .HasMaxLength(50)
                    .HasColumnName("UOM_Intl");

                entity.Property(e => e.UomUs)
                    .HasMaxLength(50)
                    .HasColumnName("UOM_US");

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqGenericSubstitution>(entity =>
            {
                entity.ToTable("CPQ_GenericSubstitution");

                entity.HasIndex(e => e.ChildGenericId, "IX_CPQ_GenericSubstitution_ChildGenericId");

                entity.HasIndex(e => e.ParentGenericId, "IX_CPQ_GenericSubstitution_ParentGenericId");

                entity.Property(e => e.Purpose).HasMaxLength(50);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.ChildGeneric)
                    .WithMany(p => p.CpqGenericSubstitutionChildGenerics)
                    .HasForeignKey(d => d.ChildGenericId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_GenericSubstitution_ChildId_FK");

                entity.HasOne(d => d.ParentGeneric)
                    .WithMany(p => p.CpqGenericSubstitutionParentGenerics)
                    .HasForeignKey(d => d.ParentGenericId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_GenericSubstitution_ParentId_FK");
            });

            modelBuilder.Entity<CpqGenericSubstitutionStaging>(entity =>
            {
                entity.ToTable("CPQ_GenericSubstitution_Staging");

                entity.Property(e => e.Purpose).HasMaxLength(50);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqGenericToGeneric>(entity =>
            {
                entity.ToTable("CPQ_GenericToGeneric");

                entity.HasIndex(e => e.ChildGenericId, "IX_CPQ_GenericToGeneric_ChildGenericId");

                entity.HasIndex(e => e.ParentGenericId, "IX_CPQ_GenericToGeneric_ParentGenericId");

                entity.Property(e => e.Optionality).HasMaxLength(20);

                entity.Property(e => e.Purpose).HasMaxLength(50);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.ChildGeneric)
                    .WithMany(p => p.CpqGenericToGenericChildGenerics)
                    .HasForeignKey(d => d.ChildGenericId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_GenericToGeneric_ChildId_FK");

                entity.HasOne(d => d.ParentGeneric)
                    .WithMany(p => p.CpqGenericToGenericParentGenerics)
                    .HasForeignKey(d => d.ParentGenericId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_GenericToGeneric_ParentId_FK");
            });

            modelBuilder.Entity<CpqGenericToGenericStaging>(entity =>
            {
                entity.ToTable("CPQ_GenericToGeneric_Staging");

                entity.Property(e => e.Optionality).HasMaxLength(20);

                entity.Property(e => e.Purpose).HasMaxLength(50);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqItem>(entity =>
            {
                entity.ToTable("CPQ_Item");

                entity.HasIndex(e => e.ItemNumber, "CPQ_Item_UC")
                    .IsUnique();

                entity.HasIndex(e => e.GenericId, "IX_CPQ_Item_GenericId");

                entity.Property(e => e.CpqSequence).HasColumnName("CPQ_Sequence");

                entity.Property(e => e.DescriptionIntl).HasMaxLength(100);

                entity.Property(e => e.DescriptionNam).HasMaxLength(100);

                entity.Property(e => e.ItemNumber).HasMaxLength(100);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.Generic)
                    .WithMany(p => p.CpqItems)
                    .HasForeignKey(d => d.GenericId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_Item_GenericId_FK");
            });

            modelBuilder.Entity<CpqItemAttributeValue>(entity =>
            {
                entity.ToTable("CPQ_ItemAttributeValue");

                entity.HasIndex(e => e.AttributeId, "IX_CPQ_ItemAttributeValue_AttributeId");

                entity.HasIndex(e => new { e.ItemId, e.AttributeId, e.Value }, "IX_CPQ_ItemAttributeValue_ItemId_AttributeId_Value");

                entity.Property(e => e.Value).HasMaxLength(800);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.Attribute)
                    .WithMany(p => p.CpqItemAttributeValues)
                    .HasForeignKey(d => d.AttributeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_ItemAttributeValue_AttributeId_FK");

                entity.HasOne(d => d.Item)
                    .WithMany(p => p.CpqItemAttributeValues)
                    .HasForeignKey(d => d.ItemId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_ItemAttributeValue_ItemId_FK");
            });

            modelBuilder.Entity<CpqItemAttributeValueStaging>(entity =>
            {
                entity.ToTable("CPQ_ItemAttributeValue_Staging");

                entity.Property(e => e.Value).HasMaxLength(800);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqItemStaging>(entity =>
            {
                entity.ToTable("CPQ_Item_Staging");

                entity.Property(e => e.CpqSequence).HasColumnName("CPQ_Sequence");

                entity.Property(e => e.DescriptionIntl).HasMaxLength(100);

                entity.Property(e => e.DescriptionNam).HasMaxLength(100);

                entity.Property(e => e.ItemNumber).HasMaxLength(100);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqLine>(entity =>
            {
                entity.ToTable("CPQ_Line");

                entity.HasIndex(e => e.FamilyId, "IX_CPQ_Line_FamilyId");

                entity.Property(e => e.LineDescription).HasMaxLength(50);

                entity.HasOne(d => d.Family)
                    .WithMany(p => p.CpqLines)
                    .HasForeignKey(d => d.FamilyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_Family_Id_FK");
            });

            modelBuilder.Entity<CpqLineAttributePurpose>(entity =>
            {
                entity.ToTable("CPQ_LineAttributePurpose");

                entity.HasIndex(e => e.AttributeId, "IX_CPQ_LineAttributePurpose_AttributeId");

                entity.HasIndex(e => e.LineId, "IX_CPQ_LineAttributePurpose_LineId");

                entity.HasIndex(e => e.PurposeId, "IX_CPQ_LineAttributePurpose_PurposeId");

                entity.Property(e => e.Active).HasMaxLength(5);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.Attribute)
                    .WithMany(p => p.CpqLineAttributePurposes)
                    .HasForeignKey(d => d.AttributeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_LineAttributePurpose_AttributeId_FK");

                entity.HasOne(d => d.Line)
                    .WithMany(p => p.CpqLineAttributePurposes)
                    .HasForeignKey(d => d.LineId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_LineAttributePurpose_LineId_FK");

                entity.HasOne(d => d.Purpose)
                    .WithMany(p => p.CpqLineAttributePurposes)
                    .HasForeignKey(d => d.PurposeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_LineAttributePurpose_PurposeId_FK");
            });

            modelBuilder.Entity<CpqLineAttributePurposeStaging>(entity =>
            {
                entity.ToTable("CPQ_LineAttributePurpose_Staging");

                entity.Property(e => e.Active).HasMaxLength(5);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqLineSellingRule>(entity =>
            {
                entity.ToTable("CPQ_LineSellingRule");

                entity.HasIndex(e => e.LineId, "IX_CPQ_LineSellingRule_LineId");

                entity.Property(e => e.CpqRatingGroup)
                    .HasMaxLength(25)
                    .HasColumnName("CPQ_RatingGroup");

                entity.Property(e => e.MaxValue).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.MinValue).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.NamIntl)
                    .HasMaxLength(4)
                    .HasColumnName("NAM_Intl");

                entity.Property(e => e.Uom)
                    .HasMaxLength(50)
                    .HasColumnName("UOM");

                entity.HasOne(d => d.Line)
                    .WithMany(p => p.CpqLineSellingRules)
                    .HasForeignKey(d => d.LineId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_LineSellingRules_LineId_FK");
            });

            modelBuilder.Entity<CpqLineSellingRuleStaging>(entity =>
            {
                entity.ToTable("CPQ_LineSellingRule_Staging");

                entity.Property(e => e.CpqRatingGroup)
                    .HasMaxLength(25)
                    .HasColumnName("CPQ_RatingGroup");

                entity.Property(e => e.MaxValue).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.MinValue).HasColumnType("numeric(18, 0)");

                entity.Property(e => e.NamIntl)
                    .HasMaxLength(4)
                    .HasColumnName("NAM_Intl");

                entity.Property(e => e.Uom)
                    .HasMaxLength(50)
                    .HasColumnName("UOM");
            });

            modelBuilder.Entity<CpqLineStaging>(entity =>
            {
                entity.ToTable("CPQ_Line_Staging");

                entity.Property(e => e.LineDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<CpqPurpose>(entity =>
            {
                entity.ToTable("CPQ_Purpose");

                entity.Property(e => e.PurposeDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<CpqPurposeStaging>(entity =>
            {
                entity.ToTable("CPQ_Purpose_Staging");

                entity.Property(e => e.PurposeDescription).HasMaxLength(50);
            });

            modelBuilder.Entity<CpqRegion>(entity =>
            {
                entity.ToTable("CPQ_Region");

                entity.Property(e => e.CpqpriceBook)
                    .HasMaxLength(255)
                    .HasColumnName("CPQPriceBook");

                entity.Property(e => e.RegionAbbreviation).HasMaxLength(50);

                entity.Property(e => e.RegionDescription).HasMaxLength(50);

                entity.Property(e => e.RegionOrgCode).HasMaxLength(20);
            });

            modelBuilder.Entity<CpqRegionCurrency>(entity =>
            {
                entity.ToTable("CPQ_RegionCurrency");

                entity.HasIndex(e => e.RegionId, "IX_CPQ_RegionCurrency_RegionId");

                entity.Property(e => e.CurrencyIsoCode).HasMaxLength(50);

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.CpqRegionCurrencies)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_CPQ_RegionCurrency_CPQ_Region");
            });

            modelBuilder.Entity<CpqRegionCurrencyStaging>(entity =>
            {
                entity.ToTable("CPQ_RegionCurrency_Staging");

                entity.Property(e => e.CurrencyIsoCode).HasMaxLength(50);
            });

            modelBuilder.Entity<CpqRegionGeneric>(entity =>
            {
                entity.ToTable("CPQ_RegionGeneric");

                entity.HasIndex(e => e.GenericId, "IX_CPQ_RegionGeneric_GenericId");

                entity.HasIndex(e => e.RegionId, "IX_CPQ_RegionGeneric_RegionId");

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.Generic)
                    .WithMany(p => p.CpqRegionGenerics)
                    .HasForeignKey(d => d.GenericId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_RegionGeneric_GenericId_FK");

                entity.HasOne(d => d.Region)
                    .WithMany(p => p.CpqRegionGenerics)
                    .HasForeignKey(d => d.RegionId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_RegionGeneric_RegionId_FK");
            });

            modelBuilder.Entity<CpqRegionGenericStaging>(entity =>
            {
                entity.ToTable("CPQ_RegionGeneric_Staging");

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqRegionStaging>(entity =>
            {
                entity.ToTable("CPQ_Region_Staging");

                entity.Property(e => e.CpqpriceBook)
                    .HasMaxLength(255)
                    .HasColumnName("CPQPriceBook");

                entity.Property(e => e.RegionAbbreviation).HasMaxLength(50);

                entity.Property(e => e.RegionDescription).HasMaxLength(50);

                entity.Property(e => e.RegionOrgCode).HasMaxLength(20);
            });

            modelBuilder.Entity<CpqRelatedSpecificSubstitution>(entity =>
            {
                entity.ToTable("CPQ_RelatedSpecificSubstitution");

                entity.HasIndex(e => e.ChildItemId, "IX_CPQ_RelatedSpecificSubstitution_ChildItemId");

                entity.HasIndex(e => e.ParentItemId, "IX_CPQ_RelatedSpecificSubstitution_ParentItemId");

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.ChildItem)
                    .WithMany(p => p.CpqRelatedSpecificSubstitutionChildItems)
                    .HasForeignKey(d => d.ChildItemId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_RelatedSpecificSubstitution_ChildId_FK");

                entity.HasOne(d => d.ParentItem)
                    .WithMany(p => p.CpqRelatedSpecificSubstitutionParentItems)
                    .HasForeignKey(d => d.ParentItemId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_RelatedSpecificSubstitution_ParentId_FK");
            });

            modelBuilder.Entity<CpqRelatedSpecificSubstitutionStaging>(entity =>
            {
                entity.ToTable("CPQ_RelatedSpecificSubstitution_Staging");

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<CpqService>(entity =>
            {
                entity.ToTable("CPQ_Service");

                entity.HasIndex(e => e.LineId, "IX_CPQ_Service_LineId");

                entity.Property(e => e.AuspacpriceBook).HasColumnName("AUSPACPriceBook");

                entity.Property(e => e.ChargeFrequency).HasMaxLength(100);

                entity.Property(e => e.ChargeMethod).HasMaxLength(100);

                entity.Property(e => e.CoeurpriceBook).HasColumnName("COEURPriceBook");

                entity.Property(e => e.Configuration).HasMaxLength(100);

                entity.Property(e => e.ConfigurationEvent).HasMaxLength(100);

                entity.Property(e => e.ConfigurationType).HasMaxLength(100);

                entity.Property(e => e.ContractedServiceField).HasMaxLength(100);

                entity.Property(e => e.ExternalId).HasMaxLength(100);

                entity.Property(e => e.ExternalId2).HasMaxLength(100);

                entity.Property(e => e.GeneratedValue).HasMaxLength(100);

                entity.Property(e => e.LineChargeId)
                    .HasMaxLength(100)
                    .HasColumnName("LineChargeID");

                entity.Property(e => e.M3itemNumber)
                    .HasMaxLength(100)
                    .HasColumnName("M3ItemNumber");

                entity.Property(e => e.M3lineType)
                    .HasMaxLength(100)
                    .HasColumnName("M3LineType");

                entity.Property(e => e.M3type)
                    .HasMaxLength(100)
                    .HasColumnName("M3Type");

                entity.Property(e => e.NampriceBook).HasColumnName("NAMPriceBook");

                entity.Property(e => e.NoeurpriceBook).HasColumnName("NOEURPriceBook");

                entity.Property(e => e.NonRentalCharge).HasMaxLength(100);

                entity.Property(e => e.OptionLayout).HasMaxLength(100);

                entity.Property(e => e.PricingMethod).HasMaxLength(100);

                entity.Property(e => e.ProductCode).HasMaxLength(100);

                entity.Property(e => e.ProductFamily).HasMaxLength(100);

                entity.Property(e => e.ProposalSection).HasMaxLength(100);

                entity.Property(e => e.RecordTypeId).HasMaxLength(100);

                entity.Property(e => e.SbqqdefaultQuantity)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQDefaultQuantity");

                entity.Property(e => e.SbqqoptionSelectionMethod)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQOptionSelectionMethod");

                entity.Property(e => e.SbqqsortOrder)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQSortOrder");

                entity.Property(e => e.SbqqsubscriptionBase)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQSubscriptionBase");

                entity.Property(e => e.SbqqsubscriptionType)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQSubscriptionType");

                entity.Property(e => e.ServiceCode).HasMaxLength(100);

                entity.Property(e => e.ShiftFactor).HasMaxLength(100);

                entity.HasOne(d => d.Line)
                    .WithMany(p => p.CpqServices)
                    .HasForeignKey(d => d.LineId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("CPQ_Serivce_CPQ_Line_FK");
            });

            modelBuilder.Entity<CpqServiceStaging>(entity =>
            {
                entity.ToTable("CPQ_Service_Staging");

                entity.Property(e => e.AuspacpriceBook).HasColumnName("AUSPACPriceBook");

                entity.Property(e => e.ChargeFrequency).HasMaxLength(100);

                entity.Property(e => e.ChargeMethod).HasMaxLength(100);

                entity.Property(e => e.CoeurpriceBook).HasColumnName("COEURPriceBook");

                entity.Property(e => e.Configuration).HasMaxLength(100);

                entity.Property(e => e.ConfigurationEvent).HasMaxLength(100);

                entity.Property(e => e.ConfigurationType).HasMaxLength(100);

                entity.Property(e => e.ContractedServiceField).HasMaxLength(100);

                entity.Property(e => e.ExternalId).HasMaxLength(100);

                entity.Property(e => e.ExternalId2).HasMaxLength(100);

                entity.Property(e => e.GeneratedValue).HasMaxLength(100);

                entity.Property(e => e.LineChargeId)
                    .HasMaxLength(100)
                    .HasColumnName("LineChargeID");

                entity.Property(e => e.M3itemNumber)
                    .HasMaxLength(100)
                    .HasColumnName("M3ItemNumber");

                entity.Property(e => e.M3lineType)
                    .HasMaxLength(100)
                    .HasColumnName("M3LineType");

                entity.Property(e => e.M3type)
                    .HasMaxLength(100)
                    .HasColumnName("M3Type");

                entity.Property(e => e.NampriceBook).HasColumnName("NAMPriceBook");

                entity.Property(e => e.NoeurpriceBook).HasColumnName("NOEURPriceBook");

                entity.Property(e => e.NonRentalCharge).HasMaxLength(100);

                entity.Property(e => e.OptionLayout).HasMaxLength(100);

                entity.Property(e => e.PricingMethod).HasMaxLength(100);

                entity.Property(e => e.ProductCode).HasMaxLength(100);

                entity.Property(e => e.ProductFamily).HasMaxLength(100);

                entity.Property(e => e.ProposalSection).HasMaxLength(100);

                entity.Property(e => e.RecordTypeId).HasMaxLength(100);

                entity.Property(e => e.SbqqdefaultQuantity)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQDefaultQuantity");

                entity.Property(e => e.SbqqoptionSelectionMethod)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQOptionSelectionMethod");

                entity.Property(e => e.SbqqsortOrder)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQSortOrder");

                entity.Property(e => e.SbqqsubscriptionBase)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQSubscriptionBase");

                entity.Property(e => e.SbqqsubscriptionType)
                    .HasMaxLength(100)
                    .HasColumnName("SBQQSubscriptionType");

                entity.Property(e => e.ServiceCode).HasMaxLength(100);

                entity.Property(e => e.ShiftFactor).HasMaxLength(100);
            });

            modelBuilder.Entity<CpqLog>(entity =>
            {
                entity.ToTable("CPQ_Log");

                entity.Property(e => e.RunOn).HasColumnType("datetime");
            });

            modelBuilder.Entity<CpqVersion>(entity =>
            {
                entity.ToTable("CPQ_Version");

                entity.Property(e => e.DataAdded).HasColumnType("datetime");

                entity.Property(e => e.VersionNumber).HasMaxLength(10);
            });

            modelBuilder.Entity<CpqVersionStaging>(entity =>
            {
                entity.ToTable("CPQ_Version_Staging");

                entity.Property(e => e.DataAdded).HasColumnType("datetime");

                entity.Property(e => e.VersionNumber).HasMaxLength(10);
            });

            modelBuilder.Entity<DataRefresh>(entity =>
            {
                entity.HasKey(e => e.Key);

                entity.ToTable("DataRefresh");

                entity.Property(e => e.Key).HasMaxLength(200);

                entity.Property(e => e.LastSuccessfulRunUtc).HasColumnName("LastSuccessfulRunUTC");
            });

            modelBuilder.Entity<Header>(entity =>
            {
                entity.HasIndex(e => e.AgreementNumber, "IX_Headers_AgreementNumber")
                    .IsUnique()
                    .HasFilter("([AgreementNumber] IS NOT NULL)");

                entity.HasIndex(e => e.AgreementNumbersOnly, "IX_Headers_AgreementNumbersOnly")
                    .HasFilter("([AgreementNumbersOnly] IS NOT NULL)");

                entity.HasIndex(e => e.OrderNumber, "IX_Headers_OrderNumber")
                    .IsUnique()
                    .HasFilter("([OrderNumber] IS NOT NULL)");

                entity.HasIndex(e => e.QuoteNumber, "IX_Headers_QuoteNumber")
                    .IsUnique()
                    .HasFilter("([QuoteNumber] IS NOT NULL)");

                entity.Property(e => e.ActivationInstanceId).HasMaxLength(500);

                entity.Property(e => e.AgreementNumber).HasMaxLength(100);

                entity.Property(e => e.AgreementNumbersOnly).HasMaxLength(100);

                entity.Property(e => e.ArmcontactEmail)
                    .HasMaxLength(500)
                    .HasColumnName("ARMContactEmail");

                entity.Property(e => e.ArmcontactName)
                    .HasMaxLength(500)
                    .HasColumnName("ARMContactName");

                entity.Property(e => e.ArmcontactPhone)
                    .HasMaxLength(500)
                    .HasColumnName("ARMContactPhone");

                entity.Property(e => e.ChangeSequence).HasDefaultValueSql("(CONVERT([bigint],(0)))");

                entity.Property(e => e.CustomerAddress).HasMaxLength(500);

                entity.Property(e => e.CustomerAddressCode).HasMaxLength(100);

                entity.Property(e => e.CustomerName).HasMaxLength(500);

                entity.Property(e => e.CustomerNumber).HasMaxLength(100);

                entity.Property(e => e.Division)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'')");

                entity.Property(e => e.Facility)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'')");

                entity.Property(e => e.OpportunityName).HasMaxLength(500);

                entity.Property(e => e.OpportunityNumber).HasMaxLength(100);

                entity.Property(e => e.OpportunityStage).HasMaxLength(100);

                entity.Property(e => e.OrderNumber).HasMaxLength(100);

                entity.Property(e => e.OrderSource)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'')");

                entity.Property(e => e.QuoteNumber).HasMaxLength(100);

                entity.Property(e => e.QuotePublicId).HasMaxLength(100);

                entity.Property(e => e.QuotePublicIdNumbersOnly).HasMaxLength(100);

                entity.Property(e => e.RentalDepot).HasMaxLength(10);

                entity.Property(e => e.Status).HasMaxLength(100);

                entity.Property(e => e.Probability).HasColumnType("float");

                entity.Property(e => e.IsSkeleton).HasDefaultValueSql("(0)");
            });

            modelBuilder.Entity<Line>(entity =>
            {
                entity.HasIndex(e => e.AgreementLineNumber, "IX_Lines_AgreementLineNumber")
                    .IsUnique()
                    .HasFilter("([AgreementLineNumber] IS NOT NULL)");

                entity.HasIndex(e => e.AgreementNumbersOnly, "IX_Lines_AgreementNumbersOnly")
                    .HasFilter("([AgreementNumbersOnly] IS NOT NULL)");

                entity.HasIndex(e => e.HeaderId, "IX_Lines_HeaderId");

                entity.HasIndex(e => e.OrderLineNumber, "IX_Lines_OrderLineNumber")
                    .HasFilter("([OrderLineNumber] IS NOT NULL)");

                entity.HasIndex(e => e.QuoteLineNumber, "IX_Lines_QuoteLineNumber")
                    .HasFilter("([QuoteLineNumber] IS NOT NULL)");

                entity.Property(e => e.ActivationInstanceId).HasMaxLength(500);

                entity.Property(e => e.AgreementLineType).HasMaxLength(200);

                entity.Property(e => e.AgreementNumbersOnly).HasMaxLength(100);

                entity.Property(e => e.Attributes).HasMaxLength(2000);

                entity.Property(e => e.LocalizedAttributes).HasMaxLength(2000);

                entity.Property(e => e.Division)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'')");

                entity.Property(e => e.Facility)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'')");

                entity.Property(e => e.GenericItemNumber).HasMaxLength(200);

                entity.Property(e => e.ItemDescription).HasMaxLength(120);

                entity.Property(e => e.ItemNumber).HasMaxLength(200);

                entity.Property(e => e.NumberOfShifts).HasMaxLength(500);

                entity.Property(e => e.OrderSource)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'')");

                entity.Property(e => e.PackageGroupNumber).HasMaxLength(200);

                entity.Property(e => e.Quantity).HasDefaultValueSql("((0.0000000000000000e+000))");

                entity.Property(e => e.QuotePublicId).HasMaxLength(100);

                entity.Property(e => e.QuotePublicIdNumbersOnly).HasMaxLength(100);

                entity.Property(e => e.RateType).HasMaxLength(500);

                entity.Property(e => e.Status).HasMaxLength(20);

                entity.Property(e => e.ValidFromDate).HasDefaultValueSql("('0001-01-01T00:00:00.0000000')");

                entity.Property(e => e.ValidToDate).HasDefaultValueSql("('0001-01-01T00:00:00.0000000')");

                entity.Property(e => e.Warehouse)
                    .HasMaxLength(200)
                    .HasDefaultValueSql("(N'')");

                entity.HasOne(d => d.Header)
                    .WithMany(p => p.Lines)
                    .HasForeignKey(d => d.HeaderId);
            });

            modelBuilder.Entity<Note>(entity =>
            {
                entity.HasIndex(e => new { e.ParentId, e.NoteType }, "IX_Notes_Column");

                entity.Property(e => e.Note1).HasColumnName("Note");

                entity.Property(e => e.NoteType).HasMaxLength(20);

                entity.Property(e => e.ParentId).HasMaxLength(20);
            });

            modelBuilder.Entity<ProductHierarchyStaging>(entity =>
            {
                entity.HasKey(e => e.IndividualItemNumber);

                entity.ToTable("ProductHierarchy_Staging");

                entity.Property(e => e.IndividualItemNumber).HasMaxLength(100);

                entity.Property(e => e.InternationalActualRatingKey).HasMaxLength(100);

                entity.Property(e => e.ProductCategory).HasMaxLength(100);

                entity.Property(e => e.ProductGroup).HasMaxLength(100);

                entity.Property(e => e.UsActualRatingKey).HasMaxLength(100);
            });

            modelBuilder.Entity<ProductItem>(entity =>
            {
                entity.HasKey(e => new { e.Warehouse, e.ItemNumber });

                entity.Property(e => e.Warehouse).HasMaxLength(100);

                entity.Property(e => e.ItemNumber).HasMaxLength(100);

                entity.Property(e => e.AllocatedQuantity).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.DefaultLocation).HasMaxLength(100);

                entity.Property(e => e.Description).HasMaxLength(100);

                entity.Property(e => e.Division).HasMaxLength(100);

                entity.Property(e => e.Facility).HasMaxLength(100);

                entity.Property(e => e.Status).HasMaxLength(100);

                entity.Property(e => e.StockQuantity).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<ProductItemsStaging>(entity =>
            {
                entity.HasKey(e => new { e.Warehouse, e.ItemNumber });

                entity.ToTable("ProductItems_Staging");

                entity.Property(e => e.Warehouse).HasMaxLength(100);

                entity.Property(e => e.ItemNumber).HasMaxLength(100);

                entity.Property(e => e.AllocatedQuantity).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.DefaultLocation).HasMaxLength(100);

                entity.Property(e => e.Description).HasMaxLength(100);

                entity.Property(e => e.Division).HasMaxLength(100);

                entity.Property(e => e.Facility).HasMaxLength(100);

                entity.Property(e => e.Status).HasMaxLength(100);

                entity.Property(e => e.StockQuantity).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<ProductItemsSyncList>(entity =>
            {
                entity.ToTable("ProductItemsSyncList");

                entity.HasIndex(e => e.ItemNumber, "UQ__ProductI__C28ACDB780085A15")
                    .IsUnique();

                entity.Property(e => e.CreatedDate).HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ItemNumber).HasMaxLength(50);
            });

            modelBuilder.Entity<Reservation>(entity =>
            {
                entity.ToTable(t =>
                {
                    t.HasTrigger("AuditReservations");
                    t.UseSqlOutputClause(false);
                });

                entity.Property(e => e.ActualAssetId).HasMaxLength(100);

                entity.Property(e => e.ActualItemNumber).HasMaxLength(100);

                entity.Property(e => e.AssetId).HasMaxLength(100);

                entity.Property(e => e.ItemNumber)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'')");

                entity.Property(e => e.Warehouse)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'')");
            });

            modelBuilder.Entity<RetrofitCache>(entity =>
            {
                entity.HasNoKey();

                entity.ToTable("RetrofitCache");

                entity.Property(e => e.Area).HasMaxLength(50);

                entity.Property(e => e.BusinessRegion).HasMaxLength(50);

                entity.Property(e => e.BusinessUnit).HasMaxLength(50);

                entity.Property(e => e.CompletedBy).HasMaxLength(500);

                entity.Property(e => e.CompletionCostCenterCode).HasMaxLength(10);

                entity.Property(e => e.CostCenterCode).HasMaxLength(10);

                entity.Property(e => e.DepotName).HasMaxLength(500);

                entity.Property(e => e.Document).HasMaxLength(500);

                entity.Property(e => e.DocumentType).HasMaxLength(3);

                entity.Property(e => e.FleetOrigin).HasMaxLength(50);

                entity.Property(e => e.FleetStatus).HasMaxLength(120);

                entity.Property(e => e.Hsbulletin)
                    .HasMaxLength(30)
                    .HasColumnName("HSBulletin");

                entity.Property(e => e.IndItem).HasMaxLength(500);

                entity.Property(e => e.InternationalActualRatingKey).HasMaxLength(126);

                entity.Property(e => e.InternationalRatingUnit).HasMaxLength(75);

                entity.Property(e => e.InternationalRatingValue).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.LocalOrProject).HasMaxLength(30);

                entity.Property(e => e.Owner).HasMaxLength(200);

                entity.Property(e => e.ProductFamily).HasMaxLength(50);

                entity.Property(e => e.ProductLine).HasMaxLength(50);

                entity.Property(e => e.Region).HasMaxLength(50);

                entity.Property(e => e.RetrofitStatus).HasMaxLength(30);

                entity.Property(e => e.ServiceCenter).HasMaxLength(50);

                entity.Property(e => e.ServiceOrder).HasMaxLength(500);

                entity.Property(e => e.Tnr)
                    .HasMaxLength(100)
                    .HasColumnName("TNR");

                entity.Property(e => e.UsActualRatingKey).HasMaxLength(126);

                entity.Property(e => e.UsratingUnit)
                    .HasMaxLength(75)
                    .HasColumnName("USRatingUnit");

                entity.Property(e => e.UsratingValue)
                    .HasColumnType("decimal(18, 2)")
                    .HasColumnName("USRatingValue");

                entity.Property(e => e.Warehouse).HasMaxLength(50);
            });

            modelBuilder.Entity<Ringfence>(entity =>
            {
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetimeoffset())");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'admin.migration@aggreko.com')");

                entity.Property(e => e.Divisions).HasDefaultValueSql("(N'')");

                entity.Property(e => e.Warehouse).HasMaxLength(100);
            });

            modelBuilder.Entity<RingfenceItem>(entity =>
            {
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetimeoffset())");

                entity.Property(e => e.CreatedBy)
                    .HasMaxLength(100)
                    .HasDefaultValueSql("(N'admin.migration@aggreko.com')");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.LoginName);

                entity.Property(e => e.LoginName).HasMaxLength(100);

                entity.Property(e => e.Division).HasMaxLength(100);

                entity.Property(e => e.FullName).HasMaxLength(100);
            });

            modelBuilder.Entity<View>(entity =>
            {
                entity.Property(e => e.Name).HasMaxLength(100);

                entity.Property(e => e.Owner).HasMaxLength(100);
            });

            modelBuilder.Entity<ViewRecipient>(entity =>
            {
                entity.HasKey(e => new { e.ViewId, e.RecipientLoginName });

                entity.HasIndex(e => new { e.RecipientLoginName, e.ViewId }, "IX_ViewRecipients_RecipientLoginName");

                entity.Property(e => e.RecipientLoginName).HasMaxLength(100);

                entity.HasOne(d => d.Recipient)
                    .WithMany(p => p.ViewRecipients)
                    .HasForeignKey(d => d.RecipientLoginName)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_ViewRecipients_Users_RecipientLoginName");

                entity.HasOne(d => d.View)
                    .WithMany(p => p.ViewRecipients)
                    .HasForeignKey(d => d.ViewId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_ViewRecipients_Views_ViewId");
            });

            modelBuilder.Entity<VwAllAttribute>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vwAllAttributes");

                entity.Property(e => e.AttributeDescription).HasMaxLength(500);

                entity.Property(e => e.AttributeName).HasMaxLength(500);

                entity.Property(e => e.Cpqattribute)
                    .HasMaxLength(40)
                    .HasColumnName("CPQAttribute");

                entity.Property(e => e.DataType).HasMaxLength(6);

                entity.Property(e => e.VerCol)
                    .IsRowVersion()
                    .IsConcurrencyToken();
            });

            modelBuilder.Entity<VwAssetItem>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vwAssetItems");

                entity.Property(e => e.AgreementNumber).HasMaxLength(100);

                entity.Property(e => e.BarData)
                    .HasMaxLength(30)
                    .IsUnicode(false);

                entity.Property(e => e.CustomerName).HasMaxLength(100);

                entity.Property(e => e.CustomerNumber).HasMaxLength(100);

                entity.Property(e => e.Description).HasMaxLength(100);

                entity.Property(e => e.Division).HasMaxLength(100);

                entity.Property(e => e.Facility).HasMaxLength(100);

                entity.Property(e => e.Id).HasMaxLength(100);

                entity.Property(e => e.ItemNumber).HasMaxLength(100);

                entity.Property(e => e.ProductCategory).HasMaxLength(100);

                entity.Property(e => e.ProductGroup).HasMaxLength(100);

                entity.Property(e => e.Remark).HasMaxLength(100);

                entity.Property(e => e.Size).HasMaxLength(100);

                entity.Property(e => e.Status).HasMaxLength(100);

                entity.Property(e => e.TelemetryStatus).HasMaxLength(100);

                entity.Property(e => e.Warehouse).HasMaxLength(100);

                entity.Property(e => e.WarehouseLocation).HasMaxLength(100);

                entity.Property(e => e.WarehouseName).HasMaxLength(100);
            });

            modelBuilder.Entity<VwHeader>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vwHeaders");

                entity.Property(e => e.AgreementNumber).HasMaxLength(100);

                entity.Property(e => e.BarData).HasMaxLength(255);

                entity.Property(e => e.CustomerAddress).HasMaxLength(500);

                entity.Property(e => e.CustomerAddressCode).HasMaxLength(100);

                entity.Property(e => e.CustomerName).HasMaxLength(500);

                entity.Property(e => e.CustomerNumber).HasMaxLength(100);

                entity.Property(e => e.Division).HasMaxLength(100);

                entity.Property(e => e.LastUpdatedByName).HasMaxLength(100);

                entity.Property(e => e.OpportunityName).HasMaxLength(500);

                entity.Property(e => e.OpportunityStage).HasMaxLength(100);

                entity.Property(e => e.OrderSource).HasMaxLength(100);

                entity.Property(e => e.Status).HasMaxLength(100);

                entity.Property(e => e.Warehouse).HasMaxLength(200);

                entity.Property(e => e.Probability).HasColumnType("float");
            });

            modelBuilder.Entity<WarehouseItem>(entity =>
            {
                entity.HasNoKey();

                entity.Property(e => e.Country).HasMaxLength(200);

                entity.Property(e => e.CountryCode).HasMaxLength(100);

                entity.Property(e => e.DivisionCode).HasMaxLength(100);

                entity.Property(e => e.Facility).HasMaxLength(100);

                entity.Property(e => e.FacilityCode).HasMaxLength(100);

                entity.Property(e => e.Warehouse).HasMaxLength(100);

                entity.Property(e => e.WarehouseCode).HasMaxLength(100);
            });

            modelBuilder.Entity<WarehouseItemsStaging>(entity =>
            {
                entity.HasKey(e => e.WarehouseCode);

                entity.ToTable("WarehouseItemsStaging");

                entity.Property(e => e.WarehouseCode).HasMaxLength(100);

                entity.Property(e => e.Country).HasMaxLength(200);

                entity.Property(e => e.CountryCode).HasMaxLength(100);

                entity.Property(e => e.DivisionCode).HasMaxLength(100);

                entity.Property(e => e.Facility).HasMaxLength(100);

                entity.Property(e => e.FacilityCode).HasMaxLength(100);

                entity.Property(e => e.Warehouse).HasMaxLength(100);
            });

            modelBuilder.Entity<ProcessingError>(entity =>
            {
                entity.HasKey(e => e.Id);

                entity.ToTable("ProcessingErrors");

                entity.HasIndex(e => e.ProcessName);
                entity.HasIndex(e => e.ProcessedAt);
                entity.HasIndex(e => e.RecordId);
                entity.HasIndex(e => e.ProcessId);

                entity.Property(e => e.ProcessName).HasMaxLength(100).IsRequired();
                entity.Property(e => e.ProcessId).HasMaxLength(100);
                entity.Property(e => e.RecordId).HasMaxLength(100);
                entity.Property(e => e.RecordType).HasMaxLength(50);
                entity.Property(e => e.ErrorMessage).IsRequired();
                entity.Property(e => e.CreatedBy).HasMaxLength(100).IsRequired();
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
