// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using OF.Data.Database;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace OF.Data
{
    public partial interface IApplicationDbContextProcedures
    {
        Task<List<CPQAvailabilitySummaryResult>> CPQAvailabilitySummaryAsync(string genericCode, string attributes, DateTime? startDate, DateTime? endDate, string division, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GenerateEventsResult>> GenerateEventsAsync(DateTime? startDate, DateTime? endDate, string divisions, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetItemsForGenericAndAttributesResult>> GetItemsForGenericAndAttributesAsync(int? genericId, string attributes, string division, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetProductAttributesForGenericResult>> GetProductAttributesForGenericAsync(int? genericId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
