//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OF.Common.Infrastructure.MDP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SalesforceSchemas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SalesforceSchemas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OF.Common.Infrastructure.MDP.Resources.SalesforceSchemas", typeof(SalesforceSchemas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;actionOverrides&quot;: [],
        ///    &quot;activateable&quot;: false,
        ///    &quot;associateEntityType&quot;: null,
        ///    &quot;associateParentEntity&quot;: null,
        ///    &quot;childRelationships&quot;: [
        ///        {
        ///            &quot;cascadeDelete&quot;: true,
        ///            &quot;childSObject&quot;: &quot;AddressHistory&quot;,
        ///            &quot;deprecatedAndHidden&quot;: false,
        ///            &quot;field&quot;: &quot;AddressId&quot;,
        ///            &quot;junctionIdListNames&quot;: [],
        ///            &quot;junctionReferenceTo&quot;: [],
        ///            &quot;relationshipName&quot;: &quot;Histories&quot;,
        ///            &quot;restrictedDelete&quot;: false
        ///        },
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;actionOverrides&quot;: [
        ///        {
        ///            &quot;formFactor&quot;: null,
        ///            &quot;isAvailableInTouch&quot;: true,
        ///            &quot;name&quot;: &quot;Edit&quot;,
        ///            &quot;pageId&quot;: &quot;0661p000000VPnlAAG&quot;,
        ///            &quot;url&quot;: &quot;https://aggreko--partial03--c.sandbox.vf.force.com/apex/EDQ_ContactPageWithPicklistTranslator?id=ENTITY_ID&quot;
        ///        },
        ///        {
        ///            &quot;formFactor&quot;: null,
        ///            &quot;isAvailableInTouch&quot;: true,
        ///            &quot;name&quot;: &quot;NewContact&quot;,
        ///            &quot;pageId&quot;: &quot;0661p000000VPnlAAG&quot;,
        ///            &quot;url&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;actionOverrides&quot;: [],
        ///    &quot;activateable&quot;: false,
        ///    &quot;associateEntityType&quot;: null,
        ///    &quot;associateParentEntity&quot;: null,
        ///    &quot;childRelationships&quot;: [
        ///        {
        ///            &quot;cascadeDelete&quot;: true,
        ///            &quot;childSObject&quot;: &quot;AgentWork&quot;,
        ///            &quot;deprecatedAndHidden&quot;: false,
        ///            &quot;field&quot;: &quot;WorkItemId&quot;,
        ///            &quot;junctionIdListNames&quot;: [],
        ///            &quot;junctionReferenceTo&quot;: [],
        ///            &quot;relationshipName&quot;: null,
        ///            &quot;restrictedDelete&quot;: false
        ///        },
        ///        {
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ProductOptions {
            get {
                return ResourceManager.GetString("ProductOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;actionOverrides&quot;: [],
        ///  &quot;activateable&quot;: false,
        ///  &quot;associateEntityType&quot;: null,
        ///  &quot;associateParentEntity&quot;: null,
        ///  &quot;childRelationships&quot;: [
        ///    {
        ///      &quot;cascadeDelete&quot;: true,
        ///      &quot;childSObject&quot;: &quot;AgentWork&quot;,
        ///      &quot;deprecatedAndHidden&quot;: false,
        ///      &quot;field&quot;: &quot;WorkItemId&quot;,
        ///      &quot;junctionIdListNames&quot;: [],
        ///      &quot;junctionReferenceTo&quot;: [],
        ///      &quot;relationshipName&quot;: null,
        ///      &quot;restrictedDelete&quot;: false
        ///    },
        ///    {
        ///      &quot;cascadeDelete&quot;: false,
        ///      &quot;childSObject&quot;: &quot;Asset&quot;,
        ///      &quot;depre [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QuoteLine {
            get {
                return ResourceManager.GetString("QuoteLine", resourceCulture);
            }
        }
    }
}
