pool:
  name: 'Self-Hosted-Ubuntu-Shared'

trigger: none
pr: none

variables:
  - template: ../actions/variables.yml

stages:
- stage: 'Build'
  displayName: 'Version, Build & Publish'
  variables:
  - group: OF-Dev

  jobs:
  - job: 'Version'
    displayName: 'Version'
    steps:
    - template: ../actions/version.yml
      parameters:
        version: $(versionWarehouses)

  - job: 'Build'
    displayName: 'Build & Publish'
    dependsOn: ["Version"]
    steps:
    - template: ../actions/build.yml
      parameters:
        workingDirectory: '$(Build.SourcesDirectory)/src'
        test: false
        artifact: true

- stage: 'Deploy_Dev'
  displayName: 'Dev Deployment'
  variables:
  - group: OF-Dev
  dependsOn: ['Build']
  jobs:
  - deployment: 'Deploy_Dev'
    displayName: 'Dev Deploy Container'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../actions/deploy-containers.yml
            parameters:
              serviceConnection: $(serviceConnection)
              registryServiceConnection: $(registryServiceConnection)
              workingDirectory: '$(Agent.BuildDirectory)/source'
              imageName: 'warehouses'
              dockerfilePath: '/OF.Data.Warehouses/Dockerfile'
              version: $(versionWarehouses)
              environment: $(environment)
              aksServiceConnection: $(aksServiceConnection)
              aksRg: $(aksRg)
              aksName: $(aksName)
              aksSub: $(aksSub)
              
- stage: 'Deploy_SIT'
  displayName: 'SIT Deployment'
  variables:
  - group: OF-SIT
  dependsOn: ['Build']
  jobs:
  - deployment: 'Deploy_SIT'
    displayName: 'SIT Deploy Container'
    environment: 'sit'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../actions/deploy-containers.yml
            parameters:
              serviceConnection: $(serviceConnection)
              registryServiceConnection: $(registryServiceConnection)
              workingDirectory: '$(Agent.BuildDirectory)/source'
              imageName: 'warehouses'
              dockerfilePath: '/OF.Data.Warehouses/Dockerfile'
              version: $(versionWarehouses)
              environment: $(environment)
              aksServiceConnection: $(aksServiceConnection)
              aksRg: $(aksRg)
              aksName: $(aksName)
              aksSub: $(aksSub)
              
- stage: 'Deploy_Test'
  displayName: 'Test Deployment'
  variables:
  - group: OF-Test
  dependsOn: ['Build']
  jobs:
  - deployment: 'Deploy_Test'
    displayName: 'Test Deploy Container'
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../actions/deploy-containers.yml
            parameters:
              serviceConnection: $(serviceConnection)
              registryServiceConnection: $(registryServiceConnection)
              workingDirectory: '$(Agent.BuildDirectory)/source'
              imageName: 'warehouses'
              dockerfilePath: '/OF.Data.Warehouses/Dockerfile'
              version: $(versionWarehouses)
              environment: $(environment)
              aksServiceConnection: $(aksServiceConnection)
              aksRg: $(aksRg)
              aksName: $(aksName)
              aksSub: $(aksSub)
              
- stage: 'Deploy_Live'
  displayName: 'Live Deployment'
  variables:
  - group: OF-Live
  dependsOn: ['Build']
  jobs:
  - deployment: 'Deploy_Live'
    displayName: 'Live Deploy Container'
    environment: 'live'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../actions/deploy-containers.yml
            parameters:
              serviceConnection: $(serviceConnectionLive)
              registryServiceConnection: $(registryServiceConnectionLive)
              workingDirectory: '$(Agent.BuildDirectory)/source'
              imageName: 'warehouses'
              dockerfilePath: '/OF.Data.Warehouses/Dockerfile'
              version: $(versionWarehouses)
              environment: $(environment)
              aksServiceConnection: $(aksServiceConnectionLive)
              aksRg: $(aksRgLive)
              aksName: $(aksNameLive)
              aksSub: $(aksSubLive)
