//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OF.Common.Infrastructure.CloudSuite.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IONSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IONSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OF.Common.Infrastructure.CloudSuite.SQL.IONSQL", typeof(IONSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	AGCN,
        ///	DIVI,
        ///	FACI,
        ///	AGNB,
        ///	ASTH,
        ///	ASTL,
        ///	AYRF,
        ///	CFJ7,
        ///	CUOR,
        ///	CUPL,
        ///	ACNM,
        ///	ADR1, 
        ///	ADR2, 
        ///	ADR3, 
        ///	ADR4,
        ///	DPOT,
        ///	SAID,
        ///	UCA2,
        ///	UCA3,
        ///	UCA4,
        ///	UCA6,
        ///	UDN1,
        ///	UDN2
        ///FROM default.staghe
        ///WHERE AGNB = &apos;A{0}&apos; OR AGNB = &apos;T{0}&apos;.
        /// </summary>
        public static string GetAgreementByAGNB {
            get {
                return ResourceManager.GetString("GetAgreementByAGNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	l.AGNB,
        ///	l.PONR,
        ///	l.POSX,
        ///	l.CONO,
        ///	l.DIVI,
        ///	l.FACI,
        ///	l.ITNO,
        ///	l.LTYP,
        ///	l.ASTH,
        ///	l.ORNO,
        ///	l.CUPL,
        ///	l.SAID,
        ///	l.FWHL,
        ///	l.DOND,
        ///	l.DOLD,
        ///	l.DONR,
        ///	l.DOLR,
        ///	l.ANOS,
        ///	l.ORQT,
        ///	l.DLDT,
        ///	l.COLD,
        ///	l.SAD1,
        ///	l.SAD2,
        ///	l.SAD3,
        ///	l.SAD4,
        ///	l.SPHN,
        ///	l.TEDA,
        ///	l.TWHL,
        ///	l.TXID,
        ///	l.DURT,
        ///	l.FVDT,
        ///	l.LVDT,
        ///	l.UCA2,
        ///	l.UCA3,
        ///	l.UCA4,
        ///	l.UDAY,
        ///	l.DETX,
        ///	l.COTX,
        ///	l.POTX,
        ///	l.PRTX,
        ///	l.BANO,
        ///	l.ILIT,
        ///	l.GEIT,
        ///	l.DETH,
        ///	l.DETM,
        ///	l.COTH,
        ///	l.CLTM,
        ///	l.CFJ4,
        ///	l.CFJ9,
        ///	l.CFJ5,
        ///	l.C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAgreementLinesByAGNB {
            get {
                return ResourceManager.GetString("GetAgreementLinesByAGNB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT
        ///    ml.SERN AS Id,
        ///    ml.SERN AS IndividualItemNumber,
        ///    ml.ITNO AS ItemNumber,
        ///    CASE 
        ///        WHEN UPPER(mitl.whsl) LIKE &apos;%-ONH&apos; THEN mitt_qlt.RORN
        ///        ELSE mitt_del.RORN
        ///    END AS TransactionReference,
        ///    CASE 
        ///        WHEN UPPER(mitl.whsl) LIKE &apos;%-ONH&apos; THEN mitt_qlt.RGDT
        ///        ELSE mitt_del.RGDT
        ///    END AS TransactionDate,
        ///    CASE 
        ///        WHEN UPPER(mitl.whsl) LIKE &apos;%-ONH&apos; THEN mitt_qlt.RGTM
        ///        ELSE mitt_del.RGTM
        ///    END AS TransactionTime,
        ///    CASE 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAssets {
            get {
                return ResourceManager.GetString("GetAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO dbo.Assets AS target
        ///USING dbo.AssetsStaging AS source
        ///ON target.Id = source.Id
        ///WHEN MATCHED THEN
        ///    UPDATE SET
        ///        target.IndividualItemNumber = source.IndividualItemNumber,
        ///        target.StatusCode = source.StatusCode,
        ///        target.Warehouse = source.Warehouse,
        ///        target.ShipAddress1 = source.ShipAddress1,
        ///        target.AgreementNumber = source.AgreementNumber,
        ///        target.DeliveryDate = source.DeliveryDate,
        ///        target.AgreementLineValidToDate = source.AgreementL [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MergeAssets {
            get {
                return ResourceManager.GetString("MergeAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO [dbo].[Assets] AS Target
        ///USING [dbo].[ProductHierarchy_Staging] AS Source
        ///ON Target.[IndividualItemNumber] = Source.[IndividualItemNumber]
        ///WHEN MATCHED THEN
        ///    UPDATE SET
        ///        Target.[ProductGroup] = Source.[ProductGroup],
        ///        Target.[ProductCategory] = Source.[ProductCategory],
        ///        Target.[InternationalSizeRating] = Source.[InternationalActualRatingKey],
        ///        Target.[UsSizeRating] = Source.[UsActualRatingKey];.
        /// </summary>
        public static string MergeHierarchy {
            get {
                return ResourceManager.GetString("MergeHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MERGE INTO [dbo].[WarehouseItems] AS Target
        ///USING [dbo].[WarehouseItemsStaging] AS Source
        ///ON Target.[WarehouseCode] = Source.[WarehouseCode]
        ///WHEN MATCHED THEN
        ///    UPDATE SET
        ///        Target.[Warehouse] = Source.[Warehouse],
        ///        Target.[DivisionCode] = Source.[DivisionCode],
        ///        Target.[FacilityCode] = Source.[FacilityCode],
        ///        Target.[Facility] = Source.[Facility],
        ///        Target.[CountryCode] = Source.[CountryCode],
        ///        Target.[Country] = Source.[Country]
        ///WHEN NOT MATCHED BY TARG [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MergeWarehouses {
            get {
                return ResourceManager.GetString("MergeWarehouses", resourceCulture);
            }
        }
    }
}
