CREATE TABLE [dbo].[ChangeOrders] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [HeaderId]             INT NOT NULL,
    [Status]               INT NOT NULL DEFAULT (0),
    [CreatedBy]            NVARCHAR (MAX)  NOT NULL,
    [CreatedDate]          DATETIME2 (7)  NOT NULL,
    [ApprovedBy]           NVARCHAR (MAX)  NULL,
    [ApprovedDate]         DATETIME2 (7)  NULL,
    [ChangeOrderHeaderId] INT NULL, 
    [SiteAddressId] INT NULL,
    [InvoiceAddressId] INT NULL,
    [PrimaryContactId] INT NULL,
    [BillingContactId] INT NULL,
    [ARMContactId] INT NULL,
    [SiteContactId] INT NULL,
    [RejectedBy] NVARCHAR(MAX) NULL, 
    [RejectedDate] DATETIME2 NULL, 
    [CompletedDate] DATETIME2 NULL, 
    CONSTRAINT [PK_ChangeOrders] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ChangeOrders_Headers_HeaderId] FOREIGN KEY ([HeaderId]) REFERENCES [dbo].[Headers] ([Id]), 
    CONSTRAINT [FK_ChangeOrders_ChangeOrderAddresses_SiteAddressId] FOREIGN KEY ([SiteAddressId]) REFERENCES [dbo].[ChangeOrderAddresses] ([Id]),
    CONSTRAINT [FK_ChangeOrders_ChangeOrderAddresses_InvoiceAddressId] FOREIGN KEY ([InvoiceAddressId]) REFERENCES [dbo].[ChangeOrderAddresses] ([Id]),
    CONSTRAINT [FK_ChangeOrders_ChangeOrderContacts_PrimaryContactId] FOREIGN KEY ([PrimaryContactId]) REFERENCES [dbo].[ChangeOrderContacts] ([Id]),
    CONSTRAINT [FK_ChangeOrders_ChangeOrderContacts_BillingContactId] FOREIGN KEY ([BillingContactId]) REFERENCES [dbo].[ChangeOrderContacts] ([Id]),
    CONSTRAINT [FK_ChangeOrders_ChangeOrderContacts_ARMContactId] FOREIGN KEY ([ARMContactId]) REFERENCES [dbo].[ChangeOrderContacts] ([Id]),
    CONSTRAINT [FK_ChangeOrders_ChangeOrderContacts_SiteContactId] FOREIGN KEY ([SiteContactId]) REFERENCES [dbo].[ChangeOrderContacts] ([Id])
);
