CREATE TABLE [dbo].[ChangeOrderHeaders] (
    [ChangeOrderId]        INT NOT NULL,
    [OnHireDate]           DATETIME2 (7)  NULL,
    [OffHireDate]          DATETIME2 (7)  NULL,
    [Price]                DECIMAL (18,2) NULL,
    [Status]               INT NOT NULL DEFAULT (0),
    [CorrelationId] NVARCHAR(500) NULL, 
    [HeaderId] INT NOT NULL, 
    [RateType] VARCHAR(200) NULL,
    [JobAIC] VARCHAR(200) NULL,
    [ProjectCode] VARCHAR(200) NULL,
    [PONumber] VARCHAR(200) NULL,
    [POAmount] VARCHAR(200) NULL,
    [RentalDuration] INT NULL,
    [MinimumRental] INT NULL,
    [DaysInWeek] INT NULL,
    [WeeksInMonth] INT NULL,
    [PriceBase] DECIMAL(18,2) NULL,
    [TargetCustomerAmount] DECIMAL(18,2) NULL,
    [PriceAdjustment] DECIMAL(18,2) NULL,
    CONSTRAINT [PK_ChangeOrderHeaders] PRIMARY KEY CLUSTERED ([ChangeOrderId] ASC),
    CONSTRAINT [FK_ChangeOrderHeaders_Headers_HeaderId] FOREIGN KEY ([HeaderId]) REFERENCES [dbo].[Headers] ([Id]),
    CONSTRAINT [FK_ChangeOrderHeaders_ChangeOrders_ChangeOrderId] FOREIGN KEY ([ChangeOrderId]) REFERENCES [dbo].[ChangeOrders] ([Id])
);
