CREATE TABLE [dbo].[CPQ_Service_Staging] (
    [Id]                         INT            IDENTITY (1, 1) NOT NULL,
    [ProductFamily]              NVARCHAR (100) NOT NULL,
    [LineId]                     INT            NOT NULL,
    [StandardPriceBook]          BIT            NOT NULL,
    [NAMPriceBook]               BIT            NOT NULL,
    [AUSPACPriceBook]            BIT            NOT NULL,
    [NOEURPriceBook]             BIT            NOT NULL,
    [COEURPriceBook]             BIT            NOT NULL,
    [MiddleEastPriceBook]        BIT            NOT NULL,
    [MexicoPriceBook]            BIT            NOT NULL,
    [ProductCode]                NVARCHAR (100) NOT NULL,
    [ServiceCode]                NVARCHAR (100) NOT NULL,
    [IsActive]                   BIT            NOT NULL,
    [M3ItemNumber]               NVARCHAR (100) NOT NULL,
    [ProductName]                NVARCHAR (MAX) NOT NULL,
    [ProductDescription]         NVARCHAR (MAX) NOT NULL,
    [M3Type]                     NVARCHAR (100) NOT NULL,
    [ShiftFactor]                NVARCHAR (100) NOT NULL,
    [IsMeter]                    BIT            NOT NULL,
    [IsFuel]                     BIT            NOT NULL,
    [Rehire]                     BIT            NOT NULL,
    [NonDiscountable]            BIT            NOT NULL,
    [QuantityEditable]           BIT            NOT NULL,
    [Component]                  BIT            NOT NULL,
    [HidePriceInSearchResults]   BIT            NOT NULL,
    [CostEditable]               BIT            NOT NULL,
    [PriceEditable]              BIT            NOT NULL,
    [PricingMethod]              NVARCHAR (100) NOT NULL,
    [ConfigurationType]          NVARCHAR (100) NOT NULL,
    [ConfigurationEvent]         NVARCHAR (100) NOT NULL,
    [OptionLayout]               NVARCHAR (100) NOT NULL,
    [ChargeMethod]               NVARCHAR (100) NOT NULL,
    [ChargeFrequency]            NVARCHAR (100) NOT NULL,
    [HasConfigurationAttributes] BIT            NOT NULL,
    [Hidden]                     BIT            NOT NULL,
    [LineChargeID]               NVARCHAR (100) NOT NULL,
    [LockDescription]            BIT            NOT NULL,
    [M3LineType]                 NVARCHAR (100) NOT NULL,
    [NonRentalCharge]            NVARCHAR (100) NOT NULL,
    [Optional]                   BIT            NOT NULL,
    [PricingMethodEditable]      BIT            NOT NULL,
    [ProposalSection]            NVARCHAR (100) NOT NULL,
    [SelectorDeselect]           BIT            NOT NULL,
    [Configuration]              NVARCHAR (100) NOT NULL,
    [ContractedServiceField]     NVARCHAR (100) NOT NULL,
    [GeneratedValue]             NVARCHAR (100) NOT NULL,
    [SBQQSortOrder]              NVARCHAR (100) NOT NULL,
    [SBQQDefaultQuantity]        NVARCHAR (100) NOT NULL,
    [SBQQOptionSelectionMethod]  NVARCHAR (100) NOT NULL,
    [SBQQSubscriptionBase]       NVARCHAR (100) NOT NULL,
    [SBQQSubscriptionType]       NVARCHAR (100) NOT NULL,
    [RecordTypeId]               NVARCHAR (100) NOT NULL,
    [ExternalId]                 NVARCHAR (100) NOT NULL,
    [ExternalId2]                NVARCHAR (100) NOT NULL,
    [AfricaPriceBook]            BIT            NOT NULL,
    [AsiaPriceBook]              BIT            NOT NULL,
    [EurasiaPriceBook]           BIT            NOT NULL,
    [LamPriceBook]               BIT            NOT NULL,
    CONSTRAINT [PK_CPQ_Service_Staging] PRIMARY KEY CLUSTERED ([Id] ASC)
);

