CREATE TABLE [dbo].[RetrofitCache] (
    [TNR]                          NVARCHAR (100)  NOT NULL,
    [BusinessRegion]               NVARCHAR (50)   NULL,
    [Region]                       NVARCHAR (50)   NULL,
    [LocalOrProject]               NVARCHAR (30)   NULL,
    [BusinessUnit]                 NVARCHAR (50)   NULL,
    [ProductFamily]                NVARCHAR (50)   NULL,
    [Area]                         NVARCHAR (50)   NULL,
    [ServiceCenter]                NVARCHAR (50)   NULL,
    [Warehouse]                    NVARCHAR (50)   NULL,
    [Owner]                        NVARCHAR (200)  NULL,
    [ProductLine]                  NVARCHAR (50)   NULL,
    [UsActualRatingKey]            NVARCHAR (126)  NULL,
    [InternationalActualRatingKey] NVARCHAR (126)  NULL,
    [IndItem]                      NVARCHAR (500)  NULL,
    [FleetOrigin]                  NVARCHAR (50)   NULL,
    [FleetStatus]                  NVARCHAR (120)  NULL,
    [CostCenterCode]               NVARCHAR (10)   NULL,
    [USRatingUnit]                 NVARCHAR (75)   NULL,
    [USRatingValue]                DECIMAL (18, 2) NULL,
    [InternationalRatingUnit]      NVARCHAR (75)   NULL,
    [InternationalRatingValue]     DECIMAL (18, 2) NULL,
    [HSBulletin]                   NVARCHAR (30)   NULL,
    [DocumentType]                 NVARCHAR (3)    NULL,
    [Document]                     NVARCHAR (500)  NULL,
    [Description]                  NVARCHAR (MAX)  NULL,
    [OpenDate]                     DATETIME2 (7)   NULL,
    [ClosedDate]                   DATETIME2 (7)   NULL,
    [CompletedDate]                DATETIME2 (7)   NULL,
    [ExpiredDate]                  DATETIME2 (7)   NULL,
    [ServiceOrder]                 NVARCHAR (500)  NULL,
    [CompletedBy]                  NVARCHAR (500)  NULL,
    [Notes]                        NVARCHAR (MAX)  NULL,
    [RetrofitStatus]               NVARCHAR (30)   NULL,
    [DepotName]                    NVARCHAR (500)  NULL,
    [BusinessHierarchyId]          INT             NULL,
    [ReleasedDate]                 DATETIME2 (7)   NULL,
    [CompletionCostCenterCode]     NVARCHAR (10)   NULL
);

