<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;CodeQL</Configurations>
    <UserSecretsId>a5a77c1c-9c35-41de-9e34-44001b1bf6a5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.2" />
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OF.Common\OF.Common.csproj" />
    <ProjectReference Include="..\OF.UI.Shared\OF.UI.Shared.csproj" />
  </ItemGroup>

</Project>
