//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OF.Tests.Data.Test.BODs.AgreementLines {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgreementLineBOD {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgreementLineBOD() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OF.Tests.Data.Test.BODs.AgreementLines.AgreementLineBOD", typeof(AgreementLineBOD).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;AcknowledgeAGKRentalAgreementLines xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.11.0&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;4.025&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.9&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-18T05:17:35.234Z&lt;/CreationDateTime&gt;
        ///        &lt;BODID&gt;e0ab48f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;AcknowledgeAGKRentalAgreementLines xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.12.2&quot; systemEnvironmentCode=&quot;Production&quot; languageCode=&quot;en-US&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;1.003&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-04-17T15:14:01.336Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;3b70e2b7-e3db-44f0-b6f2- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;AcknowledgeAGKRentalAgreementLines xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.12.2&quot; systemEnvironmentCode=&quot;Production&quot; languageCode=&quot;en-US&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;1.003&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-04-17T14:06:18.498Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;7963353c-040f-4405-82f3- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationFailed_WAD0001 {
            get {
                return ResourceManager.GetString("ActivationFailed_WAD0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;3.015&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID schemeVersionID=&quot;16.0.0.20240318172728.9&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-06-06T12:13:40.210Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;b3a7d30b-2bad-4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.011&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.9&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-18T05:18:37.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.015&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240318172728.5&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-05-21T11:00:25.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncDeleted {
            get {
                return ResourceManager.GetString("SyncDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.012&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.10&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-26T16:18:57. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncDelivered {
            get {
                return ResourceManager.GetString("SyncDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.012&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.10&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-26T16:18:57. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncDeliveredExcludedLine {
            get {
                return ResourceManager.GetString("SyncDeliveredExcludedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.012&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.10&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-26T16:18:57. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncDeliveredMatching {
            get {
                return ResourceManager.GetString("SyncDeliveredMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.012&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.10&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-26T16:18:57. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncDeliveredMatchingNotDelivered {
            get {
                return ResourceManager.GetString("SyncDeliveredMatchingNotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.012&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.10&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-26T16:18:57. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncDeliveredNonSerialized {
            get {
                return ResourceManager.GetString("SyncDeliveredNonSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;3.016&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID schemeVersionID=&quot;16.0.0.20250821122625.10&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2025-10-23T14:07:39.871Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;43d24b0e-8f82- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncDepotFulfilWithLotNumber {
            get {
                return ResourceManager.GetString("SyncDepotFulfilWithLotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;3.013&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.11&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-05-03T12:55:57.433Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;78d6abe8-aef1- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncNonSerialisedORFDelivered {
            get {
                return ResourceManager.GetString("SyncNonSerialisedORFDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;3.013&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.11&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-05-03T12:55:57.433Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;78d6abe8-aef1- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncNonSerialisedORFNotDelivered {
            get {
                return ResourceManager.GetString("SyncNonSerialisedORFNotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.012&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.10&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-26T16:18:57. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncNotDelivered {
            get {
                return ResourceManager.GetString("SyncNotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.012&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.10&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-26T16:18:57. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncNotDeliveredQty2 {
            get {
                return ResourceManager.GetString("SyncNotDeliveredQty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;3.013&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.11&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-05-02T15:38:32. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncQuantityGoesPartiallyFulfilled {
            get {
                return ResourceManager.GetString("SyncQuantityGoesPartiallyFulfilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;3.013&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.11&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-05-03T12:55:57.433Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;78d6abe8-aef1- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncSerialisedORFDelivered {
            get {
                return ResourceManager.GetString("SyncSerialisedORFDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;3.013&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.11&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-05-03T12:55:57.433Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;78d6abe8-aef1- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncSerialisedORFNotDelivered {
            get {
                return ResourceManager.GetString("SyncSerialisedORFNotDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderLine xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;3.013&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.11&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-05-03T12:55:57.433Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;78d6abe8-aef1- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SyncSerialisedQuantityGt1 {
            get {
                return ResourceManager.GetString("SyncSerialisedQuantityGt1", resourceCulture);
            }
        }
        
        internal static string SyncWithAllocationData {
            get {
                return ResourceManager.GetString("SyncWithAllocationData", resourceCulture);
            }
        }
    }
}
