//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OF.Common.Infrastructure.IPG.Orders.SOQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OFSOQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OFSOQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OF.Common.Infrastructure.IPG.Orders.SOQL.OFSOQL", typeof(OFSOQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Id,
        ///	StageName,
        ///	CAP_AG_Agreement_Number__c,
        ///	PS_AG_Effective_Probability__c,
        ///	Probability,
        ///	Account.Name,
        ///	Account.M3_Customer_Number__c,
        ///	Shipping_Address__r.CAP_AG_Street__c,
        ///	SBQQ__PrimaryQuote__c,
        ///	SBQQ__PrimaryQuote__r.Id,
        ///	SBQQ__PrimaryQuote__r.Name,
        ///	SBQQ__PrimaryQuote__r.OverviewOfServicesContent__c,
        ///	SBQQ__PrimaryQuote__r.Off_Hire_Date__c,
        ///	SBQQ__PrimaryQuote__r.On_Hire_Date__c,
        ///	SBQQ__PrimaryQuote__r.ARM_Required__c,
        ///	SBQQ__PrimaryQuote__r.ARM_Contact_Hours__c,
        ///	SBQQ__Pr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetHighProbabilityQuotes {
            get {
                return ResourceManager.GetString("GetHighProbabilityQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Id,
        ///	StageName,
        ///	CAP_AG_Agreement_Number__c,
        ///	PS_AG_Effective_Probability__c,
        ///	Probability,
        ///	Account.Name,
        ///	Account.M3_Customer_Number__c,
        ///	Shipping_Address__r.CAP_AG_Street__c,
        ///	SBQQ__PrimaryQuote__c,
        ///	SBQQ__PrimaryQuote__r.Id,
        ///	SBQQ__PrimaryQuote__r.Name,
        ///	SBQQ__PrimaryQuote__r.OverviewOfServicesContent__c,
        ///	SBQQ__PrimaryQuote__r.Off_Hire_Date__c,
        ///	SBQQ__PrimaryQuote__r.On_Hire_Date__c,
        ///	SBQQ__PrimaryQuote__r.ARM_Required__c,
        ///	SBQQ__PrimaryQuote__r.ARM_Contact_Hours__c,
        ///	SBQQ__Pr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetHighProbabilityQuotesById {
            get {
                return ResourceManager.GetString("GetHighProbabilityQuotesById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    Id,
        ///	SBQQ__Quote__c,
        ///	SBQQ__Quote__r.Id,
        ///	SBQQ__Quote__r.Name,
        ///	SBQQ__Quote__r.OverviewOfServicesContent__c,
        ///	SBQQ__Quote__r.Off_Hire_Date__c,
        ///	SBQQ__Quote__r.On_Hire_Date__c,
        ///	SBQQ__Quote__r.ARM_Required__c,
        ///	SBQQ__Quote__r.ARM_Contact_Hours__c,
        ///	SBQQ__Quote__r.ARM_Contact_Info__c,
        ///	SBQQ__Quote__r.Freight_Method__c,
        ///	SBQQ__Quote__r.Freight_Details__c,
        ///	SBQQ__Quote__r.Fuel_Service_Selected__c,
        ///	SBQQ__Quote__r.Fuel_Service_Details__c,
        ///	SBQQ__Quote__r.Operational_Requirements_Detail [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetOrder {
            get {
                return ResourceManager.GetString("GetOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    Id,
        ///	SBQQ__Quote__c,
        ///	SBQQ__Quote__r.Id,
        ///	SBQQ__Quote__r.Name,
        ///	SBQQ__Quote__r.OverviewOfServicesContent__c,
        ///	SBQQ__Quote__r.Off_Hire_Date__c,
        ///	SBQQ__Quote__r.On_Hire_Date__c,
        ///	SBQQ__Quote__r.ARM_Required__c,
        ///	SBQQ__Quote__r.ARM_Contact_Hours__c,
        ///	SBQQ__Quote__r.ARM_Contact_Info__c,
        ///	SBQQ__Quote__r.Freight_Method__c,
        ///	SBQQ__Quote__r.Freight_Details__c,
        ///	SBQQ__Quote__r.Fuel_Service_Selected__c,
        ///	SBQQ__Quote__r.Fuel_Service_Details__c,
        ///	SBQQ__Quote__r.Operational_Requirements_Detail [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetOrderByQuotePublicId {
            get {
                return ResourceManager.GetString("GetOrderByQuotePublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    Id,
        ///    Delivery_Day_Time__c,
        ///    Customer_Delivery_Date__c,
        ///    PS_AG_DeliveryStartTime__c,
        ///    PS_AG_DeliveryEndTime__c,
        ///    Onhire_Date__c,
        ///    Offhire_Date__c,
        ///    Collection_Day_Time__c,
        ///    Customer_Pickup_Date__c,
        ///    PS_AG_PickUpStartTime__c,
        ///    PS_AG_PickUpEndTime__c,
        ///    Terminated_Date__c,
        ///    PO_Number__c,
        ///    PO_Amount__c,
        ///    PS_AG_Project_Code__c,
        ///    Sales_Person_ID__c,
        ///    PS_AG_Sales_Rep__c,
        ///    Job_AIC__c,
        ///    Rental_Period__c,
        ///    M3_Rate_Type__c,
        ///    Da [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetOrderChangeorder {
            get {
                return ResourceManager.GetString("GetOrderChangeorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Id,
        ///	M3_Line_Number_Id__c,
        ///	SBQQ__QuoteLine__c,
        ///	SBQQ__QuoteLine__r.SBQQ__Number__c,
        ///	SBQQ__QuoteLine__r.Rich_Displayed_In_Line_Items_With_Attrib__c,
        ///    SBQQ__QuoteLine__r.SBQQ__Description__c,
        ///	SBQQ__QuoteLine__r.Selected_Attributes_As_Text__c,
        ///	SBQQ__QuoteLine__r.Generic_Code__c,
        ///	SBQQ__QuoteLine__r.SBQQ__Quote__c,
        ///	SBQQ__QuoteLine__r.SBQQ__Quote__r.Name,
        ///	SBQQ__QuoteLine__r.SBQQ__Group__r.Name
        ///FROM OrderItem 
        ///WHERE Id = &apos;{0}&apos;.
        /// </summary>
        public static string GetOrderLine {
            get {
                return ResourceManager.GetString("GetOrderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    Id,
        ///    On_Hire_Date__c,
        ///    Off_Hire_Date__c,
        ///    UnitPrice,
        ///    TotalPrice,
        ///    Description__c,
        ///    M3_Line_Number_Id__c,
        ///    Group_Number__c,
        ///    SBQQ__QuoteLine__r.Rate_Type__c,
        ///    SBQQ__QuoteLine__r.Price_Adjustment__c,
        ///    SBQQ__QuoteLine__r.Duration_Price2__c,
        ///    SBQQ__QuoteLine__r.SBQQ__ProductName__c,
        ///    SBQQ__QuoteLine__r.SBQQ__Quantity__c,
        ///    SBQQ__QuoteLine__r.Daily_Rate_Final__c,
        ///    SBQQ__QuoteLine__r.Adj_Daily_Rate_unit__c,
        ///    SBQQ__QuoteLine__r.Daily_F_Rate__ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetOrderLineChangeorder {
            get {
                return ResourceManager.GetString("GetOrderLineChangeorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Id,
        ///	M3_Line_Number_Id__c,
        ///	SBQQ__QuoteLine__c,
        ///	SBQQ__QuoteLine__r.SBQQ__Number__c,
        ///	SBQQ__QuoteLine__r.Rich_Displayed_In_Line_Items_With_Attrib__c,
        ///	SBQQ__QuoteLine__r.SBQQ__Description__c,
        ///	SBQQ__QuoteLine__r.Selected_Attributes_As_Text__c,
        ///	SBQQ__QuoteLine__r.Generic_Code__c,
        ///	SBQQ__QuoteLine__r.SBQQ__Quote__c,
        ///	SBQQ__QuoteLine__r.SBQQ__Quote__r.Name,
        ///	SBQQ__QuoteLine__r.SBQQ__Group__r.Name
        ///FROM OrderItem 
        ///WHERE SBQQ__QuoteLine__r.SBQQ__Quote__r.Name = &apos;{0}&apos;.
        /// </summary>
        public static string GetOrderLinesByQuotePublicId {
            get {
                return ResourceManager.GetString("GetOrderLinesByQuotePublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	Id,
        ///	StageName,
        ///	CAP_AG_Agreement_Number__c,
        ///	PS_AG_Effective_Probability__c,
        ///	Probability,
        ///	Account.Name,
        ///	Account.M3_Customer_Number__c,
        ///	Shipping_Address__r.CAP_AG_Street__c,
        ///	SBQQ__PrimaryQuote__c,
        ///	SBQQ__PrimaryQuote__r.Id,
        ///	SBQQ__PrimaryQuote__r.Name,
        ///	SBQQ__PrimaryQuote__r.OverviewOfServicesContent__c,
        ///	SBQQ__PrimaryQuote__r.Off_Hire_Date__c,
        ///	SBQQ__PrimaryQuote__r.On_Hire_Date__c,
        ///	SBQQ__PrimaryQuote__r.ARM_Required__c,
        ///	SBQQ__PrimaryQuote__r.ARM_Contact_Hours__c,
        ///	SBQQ__Pr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetQuoteById {
            get {
                return ResourceManager.GetString("GetQuoteById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    Id,
        ///    SBQQ__Number__c,
        ///    M3_Line_Type__c,
        ///    SBQQ__ProductCode__c,
        ///    SBQQ__Quantity__c,
        ///    SBQQ__Group__r.Name,
        ///	Rich_Displayed_In_Line_Items_With_Attrib__c,
        ///    SBQQ__Description__c,
        ///    Selected_Attributes_As_Text__c,
        ///    On_Hire_Date__c,
        ///    Off_Hire_Date__c,
        ///    NUMBER_OF_SHIFTS__C,
        ///	Proposal_Section__c
        ///FROM SBQQ__QuoteLine__c
        ///WHERE SBQQ__Quote__c = &apos;{0}&apos; {1}.
        /// </summary>
        public static string GetQuoteLines {
            get {
                return ResourceManager.GetString("GetQuoteLines", resourceCulture);
            }
        }
    }
}
