// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class Alert
    {
        public int Id { get; set; }
        public int LineId { get; set; }
        public string Text { get; set; } = null!;
        public string AffectedUser { get; set; } = null!;
        public bool Acknowledged { get; set; }
        public string? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
    }
}