// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class AssetsStaging
    {
        public string Id { get; set; } = null!;
        public string IndividualItemNumber { get; set; } = null!;
        public string? StatusCode { get; set; }
        public string? Warehouse { get; set; }
        public string? ShipAddress1 { get; set; }
        public string? AgreementNumber { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? AgreementLineValidToDate { get; set; }
        public DateTime? TerminationDate { get; set; }
        public string? CustomerName { get; set; }
        public string? TelemetryStatus { get; set; }
        public string? ServiceCenter { get; set; }
        public string? Description { get; set; }
        public string? Status { get; set; }
        public string? ManufacturerName { get; set; }
        public string? OwnerServiceCenter { get; set; }
        public string? CustomerNumber { get; set; }
        public string? ItemNumber { get; set; }
        public string? ShipAddress3 { get; set; }
        public string? Facility { get; set; }
        public DateTime? IonlastModified { get; set; }
        public string? WarehouseLocation { get; set; }
        public string? Division { get; set; }
        public string? Remark { get; set; }
        public string? ProductGroup { get; set; }
        public string? ProductCategory { get; set; }
        public string? InternationalSizeRating { get; set; }
        public string? UsSizeRating { get; set; }
        public double? RunHours { get; set; }
        public DateTime? EstimatedReadyDate { get; set; }
        public DateTime? AgreementLineValidFromDate { get; set; }
        public DateTime? CollectionDate { get; set; }
    }
}