// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ChangeOrderHeader
    {
        public int ChangeOrderId { get; set; }
        public DateTime? OnHireDate { get; set; }
        public DateTime? OffHireDate { get; set; }
        public decimal? Price { get; set; }
        public int Status { get; set; }
        public string? CorrelationId { get; set; }
        public int HeaderId { get; set; }
        public string? RateType { get; set; }
        public string? JobAic { get; set; }
        public string? ProjectCode { get; set; }
        public string? Ponumber { get; set; }
        public string? Poamount { get; set; }
        public int? RentalDuration { get; set; }
        public int? MinimumRental { get; set; }
        public int? DaysInWeek { get; set; }
        public int? WeeksInMonth { get; set; }
        public decimal? PriceBase { get; set; }
        public decimal? TargetCustomerAmount { get; set; }
        public decimal? PriceAdjustment { get; set; }

        public virtual ChangeOrder ChangeOrder { get; set; } = null!;
        public virtual Header Header { get; set; } = null!;
    }
}