// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ChangeOrderContact
    {
        public ChangeOrderContact()
        {
            ChangeOrderArmcontacts = new HashSet<ChangeOrder>();
            ChangeOrderBillingContacts = new HashSet<ChangeOrder>();
            ChangeOrderPrimaryContacts = new HashSet<ChangeOrder>();
            ChangeOrderSiteContacts = new HashSet<ChangeOrder>();
        }

        public int Id { get; set; }
        public int ContactType { get; set; }
        public string Title { get; set; } = null!;
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string? Phone { get; set; }
        public string? Mobile { get; set; }
        public string Email { get; set; } = null!;
        public string? Segment { get; set; }
        public string? M3number { get; set; }
        public string? SalesforceId { get; set; }

        public virtual ICollection<ChangeOrder> ChangeOrderArmcontacts { get; set; }
        public virtual ICollection<ChangeOrder> ChangeOrderBillingContacts { get; set; }
        public virtual ICollection<ChangeOrder> ChangeOrderPrimaryContacts { get; set; }
        public virtual ICollection<ChangeOrder> ChangeOrderSiteContacts { get; set; }
    }
}