// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ChangeOrder
    {
        public ChangeOrder()
        {
            ChangeOrderComments = new HashSet<ChangeOrderComment>();
            ChangeOrderLines = new HashSet<ChangeOrderLine>();
        }

        public int Id { get; set; }
        public int HeaderId { get; set; }
        public int Status { get; set; }
        public string CreatedBy { get; set; } = null!;
        public DateTime CreatedDate { get; set; }
        public string? ApprovedBy { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public int? ChangeOrderHeaderId { get; set; }
        public int? SiteAddressId { get; set; }
        public int? InvoiceAddressId { get; set; }
        public int? PrimaryContactId { get; set; }
        public int? BillingContactId { get; set; }
        public int? ArmcontactId { get; set; }
        public int? SiteContactId { get; set; }
        public string? RejectedBy { get; set; }
        public DateTime? RejectedDate { get; set; }
        public DateTime? CompletedDate { get; set; }

        public virtual ChangeOrderContact? Armcontact { get; set; }
        public virtual ChangeOrderContact? BillingContact { get; set; }
        public virtual Header Header { get; set; } = null!;
        public virtual ChangeOrderAddress? InvoiceAddress { get; set; }
        public virtual ChangeOrderContact? PrimaryContact { get; set; }
        public virtual ChangeOrderAddress? SiteAddress { get; set; }
        public virtual ChangeOrderContact? SiteContact { get; set; }
        public virtual ChangeOrderHeader? ChangeOrderHeader { get; set; }
        public virtual ICollection<ChangeOrderComment> ChangeOrderComments { get; set; }
        public virtual ICollection<ChangeOrderLine> ChangeOrderLines { get; set; }
    }
}