// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ChangeOrderComment
    {
        public int Id { get; set; }
        public int ChangeOrderId { get; set; }
        public string Comment { get; set; } = null!;
        public string CreatedBy { get; set; } = null!;
        public DateTime CreatedDate { get; set; }

        public virtual ChangeOrder ChangeOrder { get; set; } = null!;
    }
}