// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ChangeOrderLine
    {
        public int Id { get; set; }
        public int? LineId { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? OnHireDate { get; set; }
        public DateTime? OffHireDate { get; set; }
        public DateTime? TerminationDate { get; set; }
        public DateTime? CollectionDate { get; set; }
        public string Warehouse { get; set; } = null!;
        public string? GenericItemNumber { get; set; }
        public string? ItemNumber { get; set; }
        public string? Attributes { get; set; }
        public float? Quantity { get; set; }
        public decimal? Price { get; set; }
        public int Status { get; set; }
        public string? CorrelationId { get; set; }
        public int ChangeOrderId { get; set; }
        public bool Delete { get; set; }

        public virtual ChangeOrder ChangeOrder { get; set; } = null!;
        public virtual Line? Line { get; set; }
    }
}