// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ChangeOrderAddress
    {
        public ChangeOrderAddress()
        {
            ChangeOrderInvoiceAddresses = new HashSet<ChangeOrder>();
            ChangeOrderSiteAddresses = new HashSet<ChangeOrder>();
        }

        public int Id { get; set; }
        public int AddressType { get; set; }
        public string? AddressName { get; set; }
        public string? Street { get; set; }
        public string? City { get; set; }
        public string? StateOrProvince { get; set; }
        public string? ZipOrPostalCode { get; set; }
        public string? Country { get; set; }
        public string? M3number { get; set; }
        public string? SalesforceId { get; set; }

        public virtual ICollection<ChangeOrder> ChangeOrderInvoiceAddresses { get; set; }
        public virtual ICollection<ChangeOrder> ChangeOrderSiteAddresses { get; set; }
    }
}