// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace OF.Data.Database
{
    public partial class CPQAvailabilitySummaryResult
    {
        public string WarehouseCode { get; set; } = default!;
        public string Warehouse { get; set; } = default!;
        public string ItemNumber { get; set; } = default!;
        public string DescriptionIntl { get; set; } = default!;
        public int? Available { get; set; }
        public int? Count { get; set; }
    }
}
