// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqAttributeLookup
    {
        public int Id { get; set; }
        public int AttributeId { get; set; }
        public int LineId { get; set; }
        public string Value { get; set; } = null!;
    }
}