// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqAttribute
    {
        public CpqAttribute()
        {
            CpqItemAttributeValues = new HashSet<CpqItemAttributeValue>();
            CpqLineAttributePurposes = new HashSet<CpqLineAttributePurpose>();
        }

        public int Id { get; set; }
        public string AttributeDescription { get; set; } = null!;
        public string Cpqattribute1 { get; set; } = null!;
        public string? DataType { get; set; }
        public int? ValidationLength { get; set; }
        public byte[] VerCol { get; set; } = null!;
        public string? AttributeName { get; set; }

        public virtual ICollection<CpqItemAttributeValue> CpqItemAttributeValues { get; set; }
        public virtual ICollection<CpqLineAttributePurpose> CpqLineAttributePurposes { get; set; }
    }
}