// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqFamilyStaging
    {
        public int Id { get; set; }
        public string FamilyDescription { get; set; } = null!;
    }
}