// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqGeneric
    {
        public CpqGeneric()
        {
            CpqGenericSubstitutionChildGenerics = new HashSet<CpqGenericSubstitution>();
            CpqGenericSubstitutionParentGenerics = new HashSet<CpqGenericSubstitution>();
            CpqGenericToGenericChildGenerics = new HashSet<CpqGenericToGeneric>();
            CpqGenericToGenericParentGenerics = new HashSet<CpqGenericToGeneric>();
            CpqItems = new HashSet<CpqItem>();
            CpqRegionGenerics = new HashSet<CpqRegionGeneric>();
        }

        public int Id { get; set; }
        public int LineId { get; set; }
        public string GenericCode { get; set; } = null!;
        public string? GenericDescription { get; set; }
        public bool? Active { get; set; }
        public bool Deleted { get; set; }
        public int? RentalTermDays { get; set; }
        public string? UomIntl { get; set; }
        public string? RatingIntl { get; set; }
        public string? UomUs { get; set; }
        public string? RatingUs { get; set; }
        public string? Rehire { get; set; }
        public string? CableSizeAwg { get; set; }
        public string? CableSizeMm { get; set; }
        public string? AmperageLimit { get; set; }
        public string? Conductors { get; set; }
        public string? IsFuel { get; set; }
        public string? IsMeter { get; set; }
        public string? M3Type { get; set; }
        public string? CableM3itemNumber { get; set; }
        public int? CpqSequence { get; set; }
        public byte[] VerCol { get; set; } = null!;
        public string? CableType { get; set; }
        public string? ShiftFactor { get; set; }
        public string? ConfigurationType { get; set; }

        public virtual CpqLine Line { get; set; } = null!;
        public virtual ICollection<CpqGenericSubstitution> CpqGenericSubstitutionChildGenerics { get; set; }
        public virtual ICollection<CpqGenericSubstitution> CpqGenericSubstitutionParentGenerics { get; set; }
        public virtual ICollection<CpqGenericToGeneric> CpqGenericToGenericChildGenerics { get; set; }
        public virtual ICollection<CpqGenericToGeneric> CpqGenericToGenericParentGenerics { get; set; }
        public virtual ICollection<CpqItem> CpqItems { get; set; }
        public virtual ICollection<CpqRegionGeneric> CpqRegionGenerics { get; set; }
    }
}