// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqGenericToGenericStaging
    {
        public int Id { get; set; }
        public int ParentGenericId { get; set; }
        public int ChildGenericId { get; set; }
        public string Purpose { get; set; } = null!;
        public string Optionality { get; set; } = null!;
        public byte[] VerCol { get; set; } = null!;
    }
}