// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqItemStaging
    {
        public int Id { get; set; }
        public string DescriptionNam { get; set; } = null!;
        public string DescriptionIntl { get; set; } = null!;
        public string ItemNumber { get; set; } = null!;
        public int GenericId { get; set; }
        public bool? Active { get; set; }
        public bool Deleted { get; set; }
        public int? CpqSequence { get; set; }
        public byte[] VerCol { get; set; } = null!;
    }
}