// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqItemAttributeValue
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int AttributeId { get; set; }
        public string Value { get; set; } = null!;
        public byte[] VerCol { get; set; } = null!;

        public virtual CpqAttribute Attribute { get; set; } = null!;
        public virtual CpqItem Item { get; set; } = null!;
    }
}