// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqLine
    {
        public CpqLine()
        {
            CpqGenerics = new HashSet<CpqGeneric>();
            CpqLineAttributePurposes = new HashSet<CpqLineAttributePurpose>();
            CpqLineSellingRules = new HashSet<CpqLineSellingRule>();
            CpqServices = new HashSet<CpqService>();
        }

        public int Id { get; set; }
        public int FamilyId { get; set; }
        public string? LineDescription { get; set; }

        public virtual CpqFamily Family { get; set; } = null!;
        public virtual ICollection<CpqGeneric> CpqGenerics { get; set; }
        public virtual ICollection<CpqLineAttributePurpose> CpqLineAttributePurposes { get; set; }
        public virtual ICollection<CpqLineSellingRule> CpqLineSellingRules { get; set; }
        public virtual ICollection<CpqService> CpqServices { get; set; }
    }
}