// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;

namespace OF.Data.Database
{
    public partial class CpqLog
    {
        public int Id { get; set; }
        public DateTime RunOn { get; set; }
        public string RunType { get; set; } = null!;
        public string ItemType { get; set; } = null!;
        public string? Reason { get; set; }
        public string? ItemJson { get; set; }
        public bool IsError { get; set; }
    }
}
