// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqLineStaging
    {
        public int Id { get; set; }
        public int FamilyId { get; set; }
        public string? LineDescription { get; set; }
    }
}