// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqLineAttributePurpose
    {
        public int Id { get; set; }
        public int LineId { get; set; }
        public int AttributeId { get; set; }
        public int PurposeId { get; set; }
        public string Active { get; set; } = null!;
        public byte[] VerCol { get; set; } = null!;

        public virtual CpqAttribute Attribute { get; set; } = null!;
        public virtual CpqLine Line { get; set; } = null!;
        public virtual CpqPurpose Purpose { get; set; } = null!;
    }
}