// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqLineSellingRuleStaging
    {
        public int Id { get; set; }
        public int LineId { get; set; }
        public string NamIntl { get; set; } = null!;
        public string Uom { get; set; } = null!;
        public decimal? MinValue { get; set; }
        public decimal? MaxValue { get; set; }
        public string? CpqRatingGroup { get; set; }
    }
}