// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqPurpose
    {
        public CpqPurpose()
        {
            CpqLineAttributePurposes = new HashSet<CpqLineAttributePurpose>();
        }

        public int Id { get; set; }
        public string PurposeDescription { get; set; } = null!;

        public virtual ICollection<CpqLineAttributePurpose> CpqLineAttributePurposes { get; set; }
    }
}