// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqRegion
    {
        public CpqRegion()
        {
            CpqRegionCurrencies = new HashSet<CpqRegionCurrency>();
            CpqRegionGenerics = new HashSet<CpqRegionGeneric>();
        }

        public int Id { get; set; }
        public string RegionDescription { get; set; } = null!;
        public string? RegionOrgCode { get; set; }
        public string? CpqpriceBook { get; set; }
        public bool? IsActive { get; set; }
        public bool? IsStandard { get; set; }
        public string? RegionAbbreviation { get; set; }

        public virtual ICollection<CpqRegionCurrency> CpqRegionCurrencies { get; set; }
        public virtual ICollection<CpqRegionGeneric> CpqRegionGenerics { get; set; }
    }
}