// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqRegionGenericStaging
    {
        public int Id { get; set; }
        public int RegionId { get; set; }
        public int GenericId { get; set; }
        public byte[] VerCol { get; set; } = null!;
    }
}