// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqRegionCurrencyStaging
    {
        public int Id { get; set; }
        public int RegionId { get; set; }
        public string CurrencyIsoCode { get; set; } = null!;
        public bool IsActive { get; set; }
    }
}