// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqService
    {
        public int Id { get; set; }
        public string ProductFamily { get; set; } = null!;
        public int LineId { get; set; }
        public bool StandardPriceBook { get; set; }
        public bool NampriceBook { get; set; }
        public bool AuspacpriceBook { get; set; }
        public bool NoeurpriceBook { get; set; }
        public bool CoeurpriceBook { get; set; }
        public bool MiddleEastPriceBook { get; set; }
        public bool MexicoPriceBook { get; set; }
        public string ProductCode { get; set; } = null!;
        public string ServiceCode { get; set; } = null!;
        public bool IsActive { get; set; }
        public string M3itemNumber { get; set; } = null!;
        public string ProductName { get; set; } = null!;
        public string ProductDescription { get; set; } = null!;
        public string M3type { get; set; } = null!;
        public string ShiftFactor { get; set; } = null!;
        public bool IsMeter { get; set; }
        public bool IsFuel { get; set; }
        public bool Rehire { get; set; }
        public bool NonDiscountable { get; set; }
        public bool QuantityEditable { get; set; }
        public bool Component { get; set; }
        public bool HidePriceInSearchResults { get; set; }
        public bool CostEditable { get; set; }
        public bool PriceEditable { get; set; }
        public string PricingMethod { get; set; } = null!;
        public string ConfigurationType { get; set; } = null!;
        public string ConfigurationEvent { get; set; } = null!;
        public string OptionLayout { get; set; } = null!;
        public string ChargeMethod { get; set; } = null!;
        public string ChargeFrequency { get; set; } = null!;
        public bool HasConfigurationAttributes { get; set; }
        public bool Hidden { get; set; }
        public string LineChargeId { get; set; } = null!;
        public bool LockDescription { get; set; }
        public string M3lineType { get; set; } = null!;
        public string NonRentalCharge { get; set; } = null!;
        public bool Optional { get; set; }
        public bool PricingMethodEditable { get; set; }
        public string ProposalSection { get; set; } = null!;
        public bool SelectorDeselect { get; set; }
        public string Configuration { get; set; } = null!;
        public string ContractedServiceField { get; set; } = null!;
        public string GeneratedValue { get; set; } = null!;
        public string SbqqsortOrder { get; set; } = null!;
        public string SbqqdefaultQuantity { get; set; } = null!;
        public string SbqqoptionSelectionMethod { get; set; } = null!;
        public string SbqqsubscriptionBase { get; set; } = null!;
        public string SbqqsubscriptionType { get; set; } = null!;
        public string RecordTypeId { get; set; } = null!;
        public string ExternalId { get; set; } = null!;
        public string ExternalId2 { get; set; } = null!;
        public bool AfricaPriceBook { get; set; }
        public bool AsiaPriceBook { get; set; }
        public bool EurasiaPriceBook { get; set; }
        public bool LamPriceBook { get; set; }

        public virtual CpqLine Line { get; set; } = null!;
    }
}