// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class CpqVersionStaging
    {
        public int Id { get; set; }
        public string SpreadsheetName { get; set; } = null!;
        public string Application { get; set; } = null!;
        public string VersionNumber { get; set; } = null!;
        public DateTime DataAdded { get; set; }
        public bool IsLatest { get; set; }
        public string UploadedBy { get; set; } = null!;
    }
}