// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class DataRefresh
    {
        public string Key { get; set; } = null!;
        public string Description { get; set; } = null!;
        public DateTime? LastSuccessfulRunUtc { get; set; }
    }
}