// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace OF.Data.Database
{
    public partial class GenerateEventsResult
    {
        public string Id { get; set; } = default!;
        public string EventType { get; set; } = default!;
        public string? EventText { get; set; }
        public string CssClass { get; set; } = default!;
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
    }
}
