// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace OF.Data.Database
{
    public partial class GetItemsForGenericAndAttributesResult
    {
        public int Id { get; set; }
        public string DescriptionNam { get; set; } = default!;
        public string DescriptionIntl { get; set; } = default!;
        public string ItemNumber { get; set; } = default!;
        public int GenericId { get; set; }
        public bool? Active { get; set; }
        public bool Deleted { get; set; }
        public int? CPQ_Sequence { get; set; }
        public byte[] VerCol { get; set; } = default!;
    }
}
