// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace OF.Data.Database
{
    public partial class GetProductAttributesForGenericResult
    {
        public string? Name { get; set; }
        public string Value { get; set; } = default!;
    }
}
