// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class Header
    {
        public Header()
        {
            ChangeOrderHeaders = new HashSet<ChangeOrderHeader>();
            ChangeOrders = new HashSet<ChangeOrder>();
            Lines = new HashSet<Line>();
        }

        public int Id { get; set; }
        public string? QuotePublicId { get; set; }
        public string? AgreementNumber { get; set; }
        public DateTime? OnHireDate { get; set; }
        public DateTime? OffHireDate { get; set; }
        public string? Status { get; set; }
        public string? CustomerName { get; set; }
        public string? CustomerAddress { get; set; }
        public string? CustomerNumber { get; set; }
        public string Division { get; set; } = null!;
        public string? CustomerAddressCode { get; set; }
        public string OrderSource { get; set; } = null!;
        public long ChangeSequence { get; set; }
        public bool IsDeleted { get; set; }
        public int FulfilmentStatus { get; set; }
        public string? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public string Facility { get; set; } = null!;
        public string? OpportunityNumber { get; set; }
        public string? OrderNumber { get; set; }
        public string? QuoteNumber { get; set; }
        public string? AgreementNumbersOnly { get; set; }
        public string? QuotePublicIdNumbersOnly { get; set; }
        public string? OverviewOfService { get; set; }
        public double? Probability { get; set; }
        public string? ArmcontactName { get; set; }
        public string? ArmcontactEmail { get; set; }
        public string? ArmcontactPhone { get; set; }
        public int ActivationStatus { get; set; }
        public string? ActivationErrors { get; set; }
        public string? ActivationInstanceId { get; set; }
        public string? RentalDepot { get; set; }
        public string? OpportunityName { get; set; }
        public string? OpportunityStage { get; set; }
        public bool? IsSkeleton { get; set; }

        public virtual ICollection<ChangeOrderHeader> ChangeOrderHeaders { get; set; }
        public virtual ICollection<ChangeOrder> ChangeOrders { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
    }
}