// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class Line
    {
        public Line()
        {
            ChangeOrderLines = new HashSet<ChangeOrderLine>();
        }

        public int Id { get; set; }
        public int? HeaderId { get; set; }
        public string? OrderLineNumber { get; set; }
        public string? AgreementLineNumber { get; set; }
        public string? ItemNumber { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime ValidToDate { get; set; }
        public DateTime? TerminationDate { get; set; }
        public float Quantity { get; set; }
        public string? AgreementLineType { get; set; }
        public string Warehouse { get; set; } = null!;
        public string? Status { get; set; }
        public string Division { get; set; } = null!;
        public string? PackageGroupNumber { get; set; }
        public string? Attributes { get; set; }
        public string? LocalizedAttributes { get; set; }
        public DateTime ValidFromDate { get; set; }
        public long ChangeSequence { get; set; }
        public string? GenericItemNumber { get; set; }
        public bool IsDeleted { get; set; }
        public int FulfilmentStatus { get; set; }
        public double QuantityFulfilled { get; set; }
        public string? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public int? AgreementLineIndex { get; set; }
        public string Facility { get; set; } = null!;
        public int? OrderLineIndex { get; set; }
        public int? QuoteLineIndex { get; set; }
        public string? QuoteLineNumber { get; set; }
        public string OrderSource { get; set; } = null!;
        public string? AgreementNumbersOnly { get; set; }
        public string? QuotePublicId { get; set; }
        public string? QuotePublicIdNumbersOnly { get; set; }
        public string? NumberOfShifts { get; set; }
        public string? ActivationErrors { get; set; }
        public string? RateType { get; set; }
        public DateTime? CollectionDate { get; set; }
        public string? DescriptionWithAttributes { get; set; }
        public int ActivationStatus { get; set; }
        public string? ActivationInstanceId { get; set; }
        public string? ItemDescription { get; set; }
        public bool RequiresFulfilment { get; set; }

        public virtual Header? Header { get; set; }
        public virtual ICollection<ChangeOrderLine> ChangeOrderLines { get; set; }
    }
}