// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class Note
    {
        public int Id { get; set; }
        public string ParentId { get; set; } = null!;
        public string NoteType { get; set; } = null!;
        public string Note1 { get; set; } = null!;
        public string LastUpdatedBy { get; set; } = null!;
        public DateTime LastUpdatedDate { get; set; }
    }
}