// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;

namespace OF.Data.Database
{
    public partial class ProcessingError
    {
        public int Id { get; set; }
        public string ProcessName { get; set; } = null!;
        public string? ProcessId { get; set; }
        public string? RecordId { get; set; }
        public string? RecordType { get; set; }
        public string ErrorMessage { get; set; } = null!;
        public string? ErrorDetails { get; set; }
        public DateTime ProcessedAt { get; set; }
        public string CreatedBy { get; set; } = null!;
    }
}
