// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ProductHierarchyStaging
    {
        public string IndividualItemNumber { get; set; } = null!;
        public string? ProductGroup { get; set; }
        public string? ProductCategory { get; set; }
        public string? InternationalActualRatingKey { get; set; }
        public string? UsActualRatingKey { get; set; }
    }
}