// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ProductItemsStaging
    {
        public string Warehouse { get; set; } = null!;
        public string ItemNumber { get; set; } = null!;
        public decimal StockQuantity { get; set; }
        public decimal AllocatedQuantity { get; set; }
        public string? DefaultLocation { get; set; }
        public string Facility { get; set; } = null!;
        public string Division { get; set; } = null!;
        public string Status { get; set; } = null!;
        public string? Description { get; set; }
    }
}