// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class Reservation
    {
        public int Id { get; set; }
        public string AssetId { get; set; } = null!;
        public string? Notes { get; set; }
        public string ItemNumber { get; set; } = null!;
        public int Quantity { get; set; }
        public string Warehouse { get; set; } = null!;
        public int LineId { get; set; }
        public string? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public bool IsDepotFulfilled { get; set; }
        public bool IsRehire { get; set; }
        public double EffectiveQuantity { get; set; }
        public bool IsConfirmed { get; set; }
        public string? ActualAssetId { get; set; }
        public string? ActualItemNumber { get; set; }
        public double? ActualQuantity { get; set; }
    }
}