// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class RetrofitCache
    {
        public string Tnr { get; set; } = null!;
        public string? BusinessRegion { get; set; }
        public string? Region { get; set; }
        public string? LocalOrProject { get; set; }
        public string? BusinessUnit { get; set; }
        public string? ProductFamily { get; set; }
        public string? Area { get; set; }
        public string? ServiceCenter { get; set; }
        public string? Warehouse { get; set; }
        public string? Owner { get; set; }
        public string? ProductLine { get; set; }
        public string? UsActualRatingKey { get; set; }
        public string? InternationalActualRatingKey { get; set; }
        public string? IndItem { get; set; }
        public string? FleetOrigin { get; set; }
        public string? FleetStatus { get; set; }
        public string? CostCenterCode { get; set; }
        public string? UsratingUnit { get; set; }
        public decimal? UsratingValue { get; set; }
        public string? InternationalRatingUnit { get; set; }
        public decimal? InternationalRatingValue { get; set; }
        public string? Hsbulletin { get; set; }
        public string? DocumentType { get; set; }
        public string? Document { get; set; }
        public string? Description { get; set; }
        public DateTime? OpenDate { get; set; }
        public DateTime? ClosedDate { get; set; }
        public DateTime? CompletedDate { get; set; }
        public DateTime? ExpiredDate { get; set; }
        public string? ServiceOrder { get; set; }
        public string? CompletedBy { get; set; }
        public string? Notes { get; set; }
        public string? RetrofitStatus { get; set; }
        public string? DepotName { get; set; }
        public int? BusinessHierarchyId { get; set; }
        public DateTime? ReleasedDate { get; set; }
        public string? CompletionCostCenterCode { get; set; }
    }
}