// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class User
    {
        public User()
        {
            ViewRecipients = new HashSet<ViewRecipient>();
        }

        public string LoginName { get; set; } = null!;
        public string FullName { get; set; } = null!;
        public string Division { get; set; } = null!;
        public bool IsAdmin { get; set; }
        public bool IsSuperAdmin { get; set; }
        public string DateFormat { get; set; } = null!;
        public int Language { get; set; }
        public string? Roles { get; set; }
        public DateTime? LastLoginAtUtc { get; set; }

        public virtual ICollection<ViewRecipient> ViewRecipients { get; set; }
    }
}
