// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class View
    {
        public View()
        {
            ViewRecipients = new HashSet<ViewRecipient>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public int ForEveryone { get; set; }
        public string Owner { get; set; } = null!;
        public string ViewJson { get; set; } = null!;
        public string? ForDivisions { get; set; }
        public bool GanttView { get; set; }
        public bool AssetView { get; set; }

        public virtual ICollection<ViewRecipient> ViewRecipients { get; set; }
    }
}
