// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class ViewRecipient
    {
        public int ViewId { get; set; }
        public string RecipientLoginName { get; set; } = null!;

        public virtual User Recipient { get; set; } = null!;
        public virtual View View { get; set; } = null!;
    }
}
