// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class VwAllAttribute
    {
        public int Id { get; set; }
        public string AttributeDescription { get; set; } = null!;
        public string Cpqattribute { get; set; } = null!;
        public string? DataType { get; set; }
        public int? ValidationLength { get; set; }
        public byte[] VerCol { get; set; } = null!;
        public string? AttributeName { get; set; }
    }
}