// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class VwAssetItem
    {
        public string Id { get; set; } = null!;
        public string? Description { get; set; }
        public string? ItemNumber { get; set; }
        public string? Division { get; set; }
        public string? Warehouse { get; set; }
        public string? Status { get; set; }
        public string? AgreementNumber { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? LineValidTo { get; set; }
        public DateTime? LineValidFrom { get; set; }
        public DateTime? TerminationDate { get; set; }
        public DateTime? CollectionDate { get; set; }
        public string? CustomerNumber { get; set; }
        public string? CustomerName { get; set; }
        public string? Facility { get; set; }
        public string? WarehouseLocation { get; set; }
        public string WarehouseName { get; set; } = null!;
        public string? ProductGroup { get; set; }
        public string? ProductCategory { get; set; }
        public double? RunHours { get; set; }
        public DateTime? EstimatedReadyDate { get; set; }
        public string? Size { get; set; }
        public string? TelemetryStatus { get; set; }
        public string? Remark { get; set; }
        public int Family { get; set; }
        public int Line { get; set; }
        public int Generic { get; set; }
        public string? BarData { get; set; }
        public int? StatusInDateRange { get; set; }
        public int? DaysOffHire { get; set; }
    }
}