// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class VwHeader
    {
        public int Id { get; set; }
        public string? AgreementNumber { get; set; }
        public DateTime? OnHireDate { get; set; }
        public DateTime? OffHireDate { get; set; }
        public string? Status { get; set; }
        public string? CustomerName { get; set; }
        public string? CustomerAddress { get; set; }
        public string? CustomerNumber { get; set; }
        public string Division { get; set; } = null!;
        public string? CustomerAddressCode { get; set; }
        public string OrderSource { get; set; } = null!;
        public long ChangeSequence { get; set; }
        public bool IsDeleted { get; set; }
        public int FulfilmentStatus { get; set; }
        public string? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedDate { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? ValidFromDate { get; set; }
        public DateTime? ValidToDate { get; set; }
        public DateTime? TerminationDate { get; set; }
        public DateTime? CollectionDate { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? FromDateWithDelivery { get; set; }
        public DateTime? ToDate { get; set; }
        public DateTime? ToDateWithCollection { get; set; }
        public int? LineCount { get; set; }
        public int? MinFulfilmentStatus { get; set; }
        public int? MaxFulfilmentStatus { get; set; }
        public string? Warehouse { get; set; }
        public string? LastUpdatedByName { get; set; }
        public string? BarData { get; set; }
        public float? Probability { get; set; }
        public string? OpportunityName { get; set; }
        public string? OpportunityStage { get; set; }
    }
}