// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace OF.Data.Database
{
    public partial class WarehouseItem
    {
        public string WarehouseCode { get; set; } = null!;
        public string Warehouse { get; set; } = null!;
        public string DivisionCode { get; set; } = null!;
        public string FacilityCode { get; set; } = null!;
        public string Facility { get; set; } = null!;
        public string CountryCode { get; set; } = null!;
        public string Country { get; set; } = null!;
    }
}