//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OF.Tests.Data.Test.BODs.Agreements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgreementBOD {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgreementBOD() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OF.Tests.Data.Test.BODs.Agreements.AgreementBOD", typeof(AgreementBOD).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;AcknowledgeAGKRentalAgreementActivation xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.11.0&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;1.019&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.9&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-18T05:17:04.505Z&lt;/CreationDateTime&gt;
        ///        &lt;BODID&gt;f2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Activation {
            get {
                return ResourceManager.GetString("Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;AcknowledgeAGKRentalAgreementActivation xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.12.2&quot; systemEnvironmentCode=&quot;Production&quot; languageCode=&quot;en-US&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;2.008&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID&gt;M3BE&lt;/ComponentID&gt;
        ///			&lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-04-05T11:01:47.321Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;20577cf8-dd32-46ab- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationFailed {
            get {
                return ResourceManager.GetString("ActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;AcknowledgeAGKRentalAgreementActivation xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.11.0&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///	&lt;ApplicationArea&gt;
        ///		&lt;Sender&gt;
        ///			&lt;LogicalID schemeVersionID=&quot;1.020&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///			&lt;ComponentID schemeVersionID=&quot;16.0.0.20240816161447.12&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///		&lt;/Sender&gt;
        ///		&lt;CreationDateTime&gt;2024-11-05T09:52:50.507Z&lt;/CreationDateTime&gt;
        ///		&lt;BODID&gt;0c210706-35e5-42a4- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActivationFailedDirectError {
            get {
                return ResourceManager.GetString("ActivationFailedDirectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;SyncAGKRentalOrderHeader xmlns=&quot;http://schema.infor.com/InforOAGIS/2&quot; releaseID=&quot;9.2&quot; versionID=&quot;2.14.3&quot; systemEnvironmentCode=&quot;Production&quot;&gt;
        ///    &lt;ApplicationArea&gt;
        ///        &lt;Sender&gt;
        ///            &lt;LogicalID schemeVersionID=&quot;1.005&quot;&gt;lid://infor.m3.m3&lt;/LogicalID&gt;
        ///            &lt;ComponentID schemeVersionID=&quot;16.0.0.20240221054708.9&quot;&gt;M3BE&lt;/ComponentID&gt;
        ///            &lt;ConfirmationCode&gt;OnError&lt;/ConfirmationCode&gt;
        ///        &lt;/Sender&gt;
        ///        &lt;CreationDateTime&gt;2024-04-18T05:17:33 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
    }
}
