//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OF.Tests.Data.Design.dbo {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tables {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tables() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OF.Tests.Data.Design.dbo.Tables", typeof(Tables).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Alerts] (
        ///    [Id]              INT            IDENTITY (1, 1) NOT NULL,
        ///    [LineId]          INT            NOT NULL,
        ///    [Text]            NVARCHAR (MAX) NOT NULL,
        ///    [AffectedUser]    NVARCHAR (200) NOT NULL,
        ///    [Acknowledged]    BIT            NOT NULL,
        ///    [LastUpdatedBy]   NVARCHAR (MAX) NULL,
        ///    [LastUpdatedDate] DATETIME2 (7)  NULL,
        ///    CONSTRAINT [PK_Alerts] PRIMARY KEY CLUSTERED ([Id] ASC)
        ///);
        ///
        ///.
        /// </summary>
        internal static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Assets] (
        ///    [Id]                       NVARCHAR (100) NOT NULL,
        ///    [IndividualItemNumber]     NVARCHAR (100) NOT NULL,
        ///    [StatusCode]               NVARCHAR (100) NULL,
        ///    [Warehouse]                NVARCHAR (100) NULL,
        ///    [ShipAddress1]             NVARCHAR (100) NULL,
        ///    [AgreementNumber]          NVARCHAR (100) NULL,
        ///    [DeliveryDate]             DATETIME2 (7)  NULL,
        ///    [AgreementLineValidToDate] DATETIME2 (7)  NULL,
        ///    [TerminationDate]          DATETIME2 (7)  NUL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE AuditLog (
        ///    AuditLogID INT IDENTITY(1,1),
        ///    TableName VARCHAR(128) NOT NULL,
        ///    OperationType CHAR(1) NOT NULL,
        ///    NewValues NVARCHAR(MAX),
        ///    UpdateDate DATETIME NOT NULL,
        ///    UpdatedBy VARCHAR(128) NOT NULL,
        ///    [RecordId] INT NOT NULL,
        ///    CONSTRAINT PK_AuditLog PRIMARY KEY (TableName, AuditLogID)
        ///) ON AuditLogPS(TableName);.
        /// </summary>
        internal static string AuditLog {
            get {
                return ResourceManager.GetString("AuditLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE PARTITION FUNCTION AuditLogTableNamePF (VARCHAR(128))
        ///AS RANGE RIGHT FOR VALUES (&apos;Headers&apos;, &apos;Lines&apos;, &apos;Reservations&apos;); .
        /// </summary>
        internal static string AuditLogPartitionFunction {
            get {
                return ResourceManager.GetString("AuditLogPartitionFunction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE PARTITION SCHEME AuditLogPS
        ///AS PARTITION AuditLogTableNamePF
        ///TO ([Primary], [Primary], [Primary], [Primary]);.
        /// </summary>
        internal static string AuditLogPartitionScheme {
            get {
                return ResourceManager.GetString("AuditLogPartitionScheme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to --CREATE TRIGGER AuditReservations
        ///--ON Reservations
        ///--AFTER INSERT, UPDATE, DELETE
        ///--AS
        ///--BEGIN
        ///--    SET NOCOUNT ON;
        ///--    DECLARE @OperationType CHAR(1) = &apos;N&apos;, -- Default for unexpected cases
        ///--            @NewValues NVARCHAR(MAX),
        ///--            @UpdatedBy VARCHAR(128),
        ///--            @RecordId INT = 0;
        ///
        ///--    SELECT @UpdatedBy = SYSTEM_USER;
        ///
        ///--    IF EXISTS (SELECT * FROM inserted) AND EXISTS (SELECT * FROM deleted)
        ///--    BEGIN
        ///--        SET @OperationType = &apos;U&apos;;
        ///--        SET @NewValues [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuditReservations {
            get {
                return ResourceManager.GetString("AuditReservations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[CPQ_Family] (
        ///    [Id]                INT           IDENTITY (1, 1) NOT NULL,
        ///    [FamilyDescription] NVARCHAR (50) NOT NULL,
        ///    CONSTRAINT [CPQ_Family_PK] PRIMARY KEY CLUSTERED ([Id] ASC)
        ///);
        ///
        ///.
        /// </summary>
        internal static string CPQ_Family {
            get {
                return ResourceManager.GetString("CPQ_Family", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[CPQ_Generic].
        /// </summary>
        internal static string CPQ_Generic {
            get {
                return ResourceManager.GetString("CPQ_Generic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[CPQ_Item].
        /// </summary>
        internal static string CPQ_Item {
            get {
                return ResourceManager.GetString("CPQ_Item", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[CPQ_Line].
        /// </summary>
        internal static string CPQ_Line {
            get {
                return ResourceManager.GetString("CPQ_Line", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[CPQ_Service] (
        ///    [Id]                         INT            IDENTITY (1, 1) NOT NULL,
        ///    [ProductFamily]              NVARCHAR (100) NOT NULL,
        ///    [LineId]                     INT            NOT NULL,
        ///    [StandardPriceBook]          BIT            NOT NULL,
        ///    [NAMPriceBook]               BIT            NOT NULL,
        ///    [AUSPACPriceBook]            BIT            NOT NULL,
        ///    [NOEURPriceBook]             BIT            NOT NULL,
        ///    [COEURPriceBook]             BIT            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CPQ_Service {
            get {
                return ResourceManager.GetString("CPQ_Service", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DataRefresh](
        ///	[Key] NVARCHAR(200) NOT NULL,
        ///	[Description] [nvarchar](MAX) NOT NULL,
        ///	[LastSuccessfulRunUTC] DATETIME2 (7)  NULL
        ///    CONSTRAINT [PK_DataRefresh] PRIMARY KEY CLUSTERED ([Key] ASC)
        ///);
        ///
        ///
        ///.
        /// </summary>
        internal static string DataRefresh {
            get {
                return ResourceManager.GetString("DataRefresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Headers] (
        ///    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
        ///    [QuotePublicId]        NVARCHAR (100) NULL,
        ///    [AgreementNumber]      NVARCHAR (100) NULL,
        ///    [OnHireDate]           DATETIME2 (7)  NULL,
        ///    [OffHireDate]          DATETIME2 (7)  NULL,
        ///    [Status]               NVARCHAR (100) NULL,
        ///    [CustomerName]         NVARCHAR (500) NULL,
        ///    [CustomerAddress]      NVARCHAR (500) NULL,
        ///    [CustomerNumber]       NVARCHAR (100) NULL,
        ///    [Division]      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Headers {
            get {
                return ResourceManager.GetString("Headers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Lines] (
        ///    [Id]                   INT             IDENTITY (1, 1) NOT NULL,
        ///    [HeaderId]             INT             NULL,
        ///    [OrderLineNumber]      NVARCHAR (450)  NULL,
        ///    [AgreementLineNumber]  NVARCHAR (450)  NULL,
        ///    [ItemNumber]           NVARCHAR (200)  NULL,
        ///    [DeliveryDate]         DATETIME2 (7)   NULL,
        ///    [ValidToDate]          DATETIME2 (7)   DEFAULT (&apos;0001-01-01T00:00:00.0000000&apos;) NOT NULL,
        ///    [TerminationDate]      DATETIME2 (7)   NULL,
        ///    [Quantity]     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Notes]
        ///(
        ///	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
        ///    [ParentId] NVARCHAR(20) NOT NULL,
        ///    [NoteType] NVARCHAR(20) NOT NULL,
        ///    [Note] NVARCHAR(MAX) NOT NULL,
        ///    [LastUpdatedBy]     NVARCHAR (MAX) NOT NULL,
        ///    [LastUpdatedDate]   DATETIME2 (7)  NOT NULL
        ///)
        ///
        ///GO
        ///
        ///CREATE INDEX [IX_Notes_Column] ON [dbo].[Notes] ([ParentId],[NoteType])
        ///.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[ProductItems].
        /// </summary>
        internal static string ProductItems
        {
            get
            {
                return ResourceManager.GetString("ProductItems", resourceCulture);
            }
        }

/// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[ProductItemsSyncList].
        /// </summary>
        internal static string ProductItems_Staging
        {
            get
            {
                return ResourceManager.GetString("ProductItems_Staging", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[ProductItemsSyncList].
        /// </summary>
        internal static string ProductItemsSyncList
        {
            get
            {
                return ResourceManager.GetString("ProductItemsSyncList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Reservations] (
        ///    [Id]                INT            IDENTITY (1, 1) NOT NULL,
        ///    [AssetId]           NVARCHAR (100) NOT NULL,
        ///    [Notes]             NVARCHAR (MAX) NULL,
        ///    [ItemNumber]        NVARCHAR (100) DEFAULT (N&apos;&apos;) NOT NULL,
        ///    [Quantity]          INT            DEFAULT ((0)) NOT NULL,
        ///    [Warehouse]         NVARCHAR (100) DEFAULT (N&apos;&apos;) NOT NULL,
        ///    [LineId]            INT            DEFAULT ((0)) NOT NULL,
        ///    [LastUpdatedBy]     NVARCHAR (MAX) NULL,
        ///    [LastUp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Reservations {
            get {
                return ResourceManager.GetString("Reservations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[RingfenceItems] (
        ///    [Id]              INT            IDENTITY (1, 1) NOT NULL,
        ///    [RingfenceId]     INT            NULL,
        ///    [AssetId]         NVARCHAR (MAX) NOT NULL,
        ///    [LastUpdatedBy]   NVARCHAR (MAX) NULL,
        ///    [LastUpdatedDate] DATETIME2 (7)  NULL,
        ///    [CreatedAt]       DATETIMEOFFSET(7) NOT NULL CONSTRAINT [RingfenceItems_DF_CreatedAt] DEFAULT (SYSDATETIMEOFFSET()),
        ///    [CreatedBy]       NVARCHAR(100) NOT NULL CONSTRAINT [RingfenceItems_DF_CreatedBy] DEFAULT (N&apos;admin.migr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RingfenceItems {
            get {
                return ResourceManager.GetString("RingfenceItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Ringfences] (
        ///    [Id]              INT            IDENTITY (1, 1) NOT NULL,
        ///    [FromDate]        DATETIME2 (7)  NOT NULL,
        ///    [ToDate]          DATETIME2 (7)  NOT NULL,
        ///    [Title]           NVARCHAR (MAX) NOT NULL,
        ///    [LastUpdatedBy]   NVARCHAR (MAX) NULL,
        ///    [LastUpdatedDate] DATETIME2 (7)  NULL,
        ///    [Divisions]       NVARCHAR (MAX) DEFAULT (N&apos;&apos;) NOT NULL,
        ///    [Owner]           NVARCHAR(MAX) NULL,
        ///    [Warehouse]       NVARCHAR(100) NULL,
        ///    [CreatedAt]       DATETIMEO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ringfences {
            get {
                return ResourceManager.GetString("Ringfences", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[Users] (
        ///    [LoginName]    NVARCHAR (100) NOT NULL,
        ///    [FullName]     NVARCHAR (100) NOT NULL,
        ///    [Division]     NVARCHAR (100) NOT NULL,
        ///    [IsAdmin]      BIT            NOT NULL,
        ///    [IsSuperAdmin] BIT            NOT NULL,
        ///    [DateFormat]   NVARCHAR (MAX) NOT NULL,
        ///    [Language]     INT NOT NULL DEFAULT 0,
        ///    [Roles] NVARCHAR(MAX) NULL,
        ///    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([LoginName] ASC)
        ///);
        ///
        ///.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[ProcessingErrors] (
        ///    [Id]                INT IDENTITY(1,1) NOT NULL,
        ///    [ProcessName]       NVARCHAR(100) NOT NULL,
        ///    [ProcessId]         NVARCHAR(100) NULL,
        ///    [RecordId]          NVARCHAR(100) NULL,
        ///    [RecordType]        NVARCHAR(50) NULL,
        ///    [ErrorMessage]      NVARCHAR(MAX) NOT NULL,
        ///    [ErrorDetails]      NVARCHAR(MAX) NULL,
        ///    [ProcessedAt]       DATETIME2(7) NOT NULL DEFAULT GETUTCDATE(),
        ///    [CreatedBy]         NVARCHAR(100) NOT NULL DEFAULT 'System'
        /// );
        ///
        internal static string ProcessingErrors
        {
            get
            {
                return ResourceManager.GetString("ProcessingErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[WarehouseItems] (
        ///    [WarehouseCode] NVARCHAR (100) NOT NULL,
        ///    [Warehouse]     NVARCHAR (100) NOT NULL,
        ///    [DivisionCode]  NVARCHAR (100) NOT NULL,
        ///    [FacilityCode]  NVARCHAR (100) NOT NULL,
        ///    [Facility]      NVARCHAR (100) NOT NULL,
        ///    [CountryCode]   NVARCHAR (100) NOT NULL,
        ///    [Country]       NVARCHAR (200) NOT NULL
        ///);
        ///
        internal static string WarehouseItems {
            get {
                return ResourceManager.GetString("WarehouseItems", resourceCulture);
            }
        }

        internal static string AttributeLanguage {
            get {
                return ResourceManager.GetString("AttributeLanguage", resourceCulture);
            }
        }

        internal static string CPQ_Attribute {
            get {
                return ResourceManager.GetString("CPQ_Attribute", resourceCulture);
            }
        }

        internal static string CPQ_GenericSubstitution {
            get {
                return ResourceManager.GetString("CPQ_GenericSubstitution", resourceCulture);
            }
        }

        internal static string CPQ_ItemAttributeValue {
            get {
                return ResourceManager.GetString("CPQ_ItemAttributeValue", resourceCulture);
            }
        }

        internal static string CPQ_LineAttributePurpose {
            get {
                return ResourceManager.GetString("CPQ_LineAttributePurpose", resourceCulture);
            }
        }

        internal static string CPQ_Purpose {
            get {
                return ResourceManager.GetString("CPQ_Purpose", resourceCulture);
            }
        }

        internal static string CPQ_RelatedSpecificSubstitution {
            get {
                return ResourceManager.GetString("CPQ_RelatedSpecificSubstitution", resourceCulture);
            }
        }
    }
}
