<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<NoWarn>CS8618,CS8600,CS8602,CS8603,CS8604</NoWarn>
		<Configurations>Debug;Release;CodeQL</Configurations>
		<UserSecretsId>a5a77c1c-9c35-41de-9e34-44001b1bf6a5</UserSecretsId>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.17.4" />
		<PackageReference Include="HtmlAgilityPack" Version="1.11.62" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OF.Common\OF.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
